export const DISTRITOS = [
  "Aveiro",
  "Beja",
  "Braga",
  "Bragança",
  "Castelo Branco",
  "Coimbra",
  "Évora",
  "Faro",
  "Guarda",
  "Leiria",
  "Lisboa",
  "Portalegre",
  "Porto",
  "Santarém",
  "Setúbal",
  "Viana do Castelo",
  "Vila Real",
  "Viseu",
];

export const DISTRITO_MUNICIPIOS: { [key: string]: string[] } = {
  Aveiro: [
    "Águeda",
    "Albergaria-a-Velha",
    "Anadia",
    "Arouca",
    "Aveiro",
    "Castelo de Paiva",
    "Espinho",
    "Estarreja",
    "Ílhavo",
    "Mealhada",
    "Murtosa",
    "Oliveira de Azeméis",
    "Oliveira do Bairro",
    "Ovar",
    "Santa Maria da Feira",
    "São João da Madeira",
    "Sever do Vouga",
    "Vagos",
    "Vale de Cambra",
  ],
  Beja: [
    "Aljustrel",
    "Almodôvar",
    "Alvito",
    "Barrancos",
    "Beja",
    "Castro Verde",
    "Cuba",
    "Ferreira do Alentejo",
    "Mértola",
    "Moura",
    "Odemira",
    "Ourique",
    "Serpa",
    "Vidigueira",
  ],
  Braga: [
    "Amares",
    "Barcelos",
    "Braga",
    "Cabeceiras de Basto",
    "Fafe",
    "Guimarães",
    "Póvoa de Lanhoso",
    "Terras de Bouro",
    "Vieira do Minho",
    "Vila Nova de Famalicão",
    "Vila Verde",
  ],
  Bragança: [
    "Alfândega da Fé",
    "Bragança",
    "Carrazeda de Ansiães",
    "Freixo de Espada à Cinta",
    "Macedo de Cavaleiros",
    "Miranda do Douro",
    "Mirandela",
    "Mogadouro",
    "Torre de Moncorvo",
    "Vila Flor",
    "Vimioso",
    "Vinhais",
  ],
  "Castelo Branco": [
    "Belmonte",
    "Castelo Branco",
    "Covilhã",
    "Fundão",
    "Idanha-a-Nova",
    "Oleiros",
    "Penamacor",
    "Proença-a-Nova",
    "Sertã",
    "Vila de Rei",
    "Vila Velha de Ródão",
  ],
  Coimbra: [
    "Arganil",
    "Cantanhede",
    "Coimbra",
    "Condeixa-a-Nova",
    "Figueira da Foz",
    "Góis",
    "Lousã",
    "Mira",
    "Miranda do Corvo",
    "Montemor-o-Velho",
    "Oliveira do Hospital",
    "Penacova",
    "Pombal",
    "Soure",
  ],
  Évora: [
    "Alandroal",
    "Arraiolos",
    "Borba",
    "Estremoz",
    "Évora",
    "Montemor-o-Novo",
    "Moura",
    "Portel",
    "Redondo",
    "Reguengos de Monsaraz",
    "Vendas Novas",
    "Viana do Alentejo",
    "Vila Viçosa",
  ],
  Faro: [
    "Albufeira",
    "Alcoutim",
    "Aljezur",
    "Castro Marim",
    "Faro",
    "Lagoa",
    "Lagos",
    "Loulé",
    "Monchique",
    "Olhão",
    "Portimão",
    "São Brás de Alportel",
    "Silves",
    "Tavira",
    "Vila do Bispo",
    "Vila Real de Santo António",
  ],
  Guarda: [
    "Aguiar da Beira",
    "Almeida",
    "Celorico da Beira",
    "Figueira de Castelo Rodrigo",
    "Guarda",
    "Manteigas",
    "Mêda",
    "Pinhel",
    "Sabugal",
    "Seia",
    "Trancoso",
  ],
  Leiria: [
    "Alcobaça",
    "Alvaiázere",
    "Ansião",
    "Batalha",
    "Bombarral",
    "Caldas da Rainha",
    "Castanheira de Pera",
    "Figueiró dos Vinhos",
    "Leiria",
    "Marinha Grande",
    "Nazaré",
    "Óbidos",
    "Pedrógão Grande",
    "Peniche",
    "Pombal",
  ],
  Lisboa: [
    "Alenquer",
    "Amadora",
    "Arruda dos Vinhos",
    "Azambuja",
    "Cadaval",
    "Cascais",
    "Lisboa",
    "Loures",
    "Lourinhã",
    "Mafra",
    "Odivelas",
    "Oeiras",
    "Sintra",
    "Sobral de Monte Agraço",
    "Torres Vedras",
  ],
  Portalegre: [
    "Alter do Chão",
    "Arronches",
    "Avis",
    "Campo Maior",
    "Castelo de Vide",
    "Crato",
    "Elvas",
    "Fronteira",
    "Gavião",
    "Marvão",
    "Monforte",
    "Nisa",
    "Portalegre",
  ],
  Porto: [
    "Amarante",
    "Baixa da Banheira",
    "Barcelos",
    "Braga",
    "Câmara de Lobos",
    "Felgueiras",
    "Gondomar",
    "Lousada",
    "Maia",
    "Matosinhos",
    "Paços de Ferreira",
    "Paredes",
    "Penafiel",
    "Porto",
    "Póvoa de Varzim",
    "Santo Tirso",
    "Trofa",
    "Valongo",
    "Vila do Conde",
    "Vila Nova de Gaia",
  ],
  Santarém: [
    "Abrantes",
    "Alcanena",
    "Almeirim",
    "Benavente",
    "Cartaxo",
    "Chamusca",
    "Constância",
    "Coruche",
    "Entroncamento",
    "Ferreira do Zêzere",
    "Golegã",
    "Mação",
    "Ourém",
    "Rio Maior",
    "Salvaterra de Magos",
    "Santarém",
    "Sardoal",
    "Tomar",
    "Torres Novas",
  ],
  Setúbal: [
    "Alcácer do Sal",
    "Alcochete",
    "Almada",
    "Barreiro",
    "Grândola",
    "Moita",
    "Montijo",
    "Palmela",
    "Santiago do Cacém",
    "Seixal",
    "Setúbal",
    "Sesimbra",
    "Sines",
  ],
  "Viana do Castelo": [
    "Arcos de Valdevez",
    "Caminha",
    "Melgaço",
    "Monção",
    "Paredes de Coura",
    "Ponte de Lima",
    "Viana do Castelo",
    "Vila Nova de Cerveira",
  ],
  "Vila Real": [
    "Alijó",
    "Boticas",
    "Chaves",
    "Mesão Frio",
    "Mondim de Basto",
    "Montalegre",
    "Peso da Régua",
    "Ribeira de Pena",
    "Sabrosa",
    "Santa Marta de Penaguião",
    "Valpaços",
    "Vila Pouca de Aguiar",
    "Vila Real",
  ],
  Viseu: [
    "Armamar",
    "Carregal do Sal",
    "Castro Daire",
    "Cinfães",
    "Lamego",
    "Mangualde",
    "Moimenta da Beira",
    "Nelas",
    "Oliveira de Frades",
    "Penalva do Castelo",
    "Penedono",
    "Resende",
    "Santa Comba Dão",
    "São João da Pesqueira",
    "Sátão",
    "Tondela",
    "Vila Nova de Paiva",
    "Viseu",
  ],
};

export const MUNICIPIO_FREGUESIAS: { [key: string]: string[] } = {
  // Aveiro
  "Águeda": ["Águeda", "Belazaima do Chão", "Borralha", "Fermentelos", "Macinhata do Vouga", "Recardães", "Trofa", "Valongo do Vouga"],
  "Albergaria-a-Velha": ["Albergaria-a-Velha", "Alquerubim", "Angeja", "Branca", "Ribeira de Fráguas", "São João de Loure"],
  "Anadia": ["Anadia", "Arcos", "Avelãs de Caminho", "Avelãs de Cima", "Moita", "Mogofores", "Paredes do Bairro", "São Lourenço do Bairro", "Tamengos", "Vilarinho do Bairro"],
  "Arouca": ["Arouca", "Burgo", "Canelas", "Chave", "Covelo de Paivó", "Escariz", "Fermedo", "Mansores", "Moldes", "Santa Eulália", "São Miguel do Mato", "Tropeço", "Urrô", "Várzea"],
  "Aveiro": ["Aradas", "Cacia", "Eirol", "Esgueira", "Glória", "Nariz", "Oliveirinha", "Requeixo", "Santa Joana", "São Bernardo", "São Jacinto", "Vera Cruz"],
  "Castelo de Paiva": ["Bairros", "Fornos", "Pedorido", "Raiva", "Real", "Sobrado", "Vila Chã"],
  "Espinho": ["Anta", "Espinho", "Guetim", "Paramos", "Silvalde"],
  "Estarreja": ["Avanca", "Beduído", "Canelas", "Fermelã", "Pardilhó", "Salreu", "Veiros"],
  "Ílhavo": ["Gafanha da Encarnação", "Gafanha da Nazaré", "Gafanha do Carmo", "Ílhavo"],
  "Mealhada": ["Barcouço", "Casal Comba", "Luso", "Mealhada", "Pampilhosa", "Vacariça", "Ventosa do Bairro"],
  "Murtosa": ["Bunheiro", "Monte", "Murtosa", "Torreira"],
  "Oliveira de Azeméis": ["Carregosa", "Cesar", "Fajões", "Loureiro", "Macinhata da Seixa", "Macieira de Sarnes", "Madail", "Nogueira do Cravo", "Oliveira de Azeméis", "Ossela", "Palmaz", "Pindelo", "Santiago de Riba-Ul", "São Martinho da Gândara", "São Roque", "Ul", "Vila de Cucujães"],
  "Oliveira do Bairro": ["Bustos", "Mamarrosa", "Oiã", "Oliveira do Bairro", "Palhaça"],
  "Ovar": ["Arada", "Cortegaça", "Esmoriz", "Maceda", "Ovar", "São João", "São Vicente de Pereira Jusã", "Válega"],
  "Santa Maria da Feira": ["Argoncilhe", "Arrifana", "Caldas de São Jorge", "Canedo", "Escapães", "Fiães", "Lobão", "Lourosa", "Milheirós de Poiares", "Mozelos", "Nogueira da Regedoura", "Paços de Brandão", "Pigeiros", "Rio Meão", "Romariz", "Sanfins", "Santa Maria da Feira", "Santa Maria de Lamas", "São Paio de Oleiros", "Sanguedo", "São João de Ver", "Vila Maior"],
  "São João da Madeira": ["São João da Madeira"],
  "Sever do Vouga": ["Cedrim", "Couto de Esteves", "Paradela", "Pessegueiro do Vouga", "Rocas do Vouga", "Sever do Vouga", "Silva Escura", "Talhadas"],
  "Vagos": ["Calvão", "Fonte de Angeão", "Gafanha da Boa Hora", "Ouca", "Ponte de Vagos", "Santo André de Vagos", "Santo António de Vagos", "Soza", "Vagos"],
  "Vale de Cambra": ["Arões", "Cepelos", "Codal", "Junqueira", "Macieira de Cambra", "Roge", "São Pedro de Castelões", "Vila Chã"],

  // Porto
  "Porto": ["Aldoar", "Bonfim", "Campanhã", "Cedofeita", "Foz do Douro", "Lordelo do Ouro", "Massarelos", "Miragaia", "Nevogilde", "Paranhos", "Ramalde", "Santo Ildefonso", "São Nicolau", "Sé", "Vitória"],
  "Vila Nova de Gaia": ["Arcozelo", "Avintes", "Canelas", "Canidelo", "Gulpilhares", "Grijó", "Madalena", "Mafamude", "Oliveira do Douro", "Pedroso", "Sandim", "Santa Marinha", "São Félix da Marinha", "São Pedro da Afurada", "Serzedo", "Valadares", "Vilar de Andorinho", "Vilar do Paraíso"],
  "Matosinhos": ["Custóias", "Guifões", "Lavra", "Leça da Palmeira", "Leça do Balio", "Matosinhos", "Perafita", "Santa Cruz do Bispo", "São Mamede de Infesta", "Senhora da Hora"],
  "Gondomar": ["Baguim do Monte", "Covelo", "Fânzeres", "Foz do Sousa", "Gondomar", "Lomba", "Melres", "Rio Tinto", "São Cosme", "São Pedro da Cova", "Valbom"],
  "Maia": ["Águas Santas", "Barca", "Cidade da Maia", "Folgosa", "Gemunde", "Gueifães", "Milheirós", "Moreira", "Nogueira", "Pedrouços", "Santa Maria de Avioso", "São Pedro de Avioso", "Silva Escura", "Vermoim", "Vila Nova da Telha"],
  "Valongo": ["Alfena", "Campo", "Ermesinde", "Sobrado", "Valongo"],
  "Paredes": ["Aguiar de Sousa", "Astromil", "Baltar", "Beire", "Besteiros", "Bitarães", "Castelões de Cepeda", "Cristelo", "Duas Igrejas", "Gandra", "Gondalães", "Lordelo", "Louredo", "Madalena", "Parada de Todeia", "Paredes", "Rebordosa", "Recarei", "Sobreira", "Sobrosa", "Vandoma", "Vilela"],
  "Penafiel": ["Abragão", "Boelhe", "Bustelo", "Cabeça Santa", "Canelas", "Castelões", "Croca", "Duas Igrejas", "Eja", "Fonte Arcada", "Galegos", "Guilhufe", "Irivo", "Lagares", "Luzim", "Milhundos", "Novelas", "Oldrões", "Paço de Sousa", "Perozelo", "Pinheiro", "Portela", "Rans", "Recezinhos", "Rio Mau", "São Martinho de Recezinhos", "Sebolido", "Valpedre", "Vila Cova"],
  "Amarante": ["Aboadela", "Ansiães", "Amarante", "Ataíde", "Bustelo", "Canadelo", "Cepelos", "Figueiró", "Freixo de Baixo", "Freixo de Cima", "Fridão", "Gatão", "Gondar", "Gouveia", "Jazente", "Lufrei", "Madalena", "Padronelo", "Carneiro", "Real", "Rebordelo", "Salvador do Monte", "São Gonçalo", "Telões", "Travanca", "Vila Caiz", "Vila Chã do Marão", "Vila Garcia"],
  "Felgueiras": ["Airães", "Borba de Godim", "Caramos", "Friande", "Idães", "Jugueiros", "Lagares", "Lixa", "Margaride", "Milhundos", "Moure", "Pedreira", "Pinheiro", "Pombeiro de Ribavizela", "Refontoura", "Regilde", "Revinhade", "Santão", "São Jorge de Vizela", "São Simão de Vizela", "Sendim", "Sernande", "Torrados", "Unhão", "Varziela", "Várzea"],
  "Lousada": ["Aveleda", "Boim", "Caíde de Rei", "Casais", "Cernadelo", "Covas", "Cristelos", "Figueiras", "Lodares", "Lousada", "Lustosa", "Macieira", "Meinedo", "Nevogilde", "Nespereira", "Ordem", "Pias", "Santa Margarida", "Sousela", "Torno", "Vilar do Torno"],
  "Paços de Ferreira": ["Carvalhosa", "Eiriz", "Figueiró", "Frazão", "Lamoso", "Meixomil", "Modelos", "Paços de Ferreira", "Penamaior", "Raimonda", "Sanfins de Ferreira", "Seroa"],
  "Santo Tirso": ["Agrela", "Areias", "Burgães", "Campo", "Carreira", "Guimarei", "Lamelas", "Lama", "Monte Córdova", "Negrelos", "Refojos de Riba de Ave", "Reguenga", "Roriz", "Santão", "Santo Tirso", "São Mamede de Negrelos", "São Martinho do Campo", "São Miguel do Couto", "São Tomé de Negrelos", "Sequeira", "Vila das Aves", "Vilarinho"],
  "Trofa": ["Alvarelhos", "Bougado", "Coronado", "Covelas", "Guidões", "Muro", "Santiago de Bougado", "São Martinho de Bougado", "São Mamede de Coronado", "São Romão de Coronado"],
  "Vila do Conde": ["Árvore", "Aveleda", "Azurara", "Bagunte", "Fajozes", "Ferreiró", "Fornelo", "Gião", "Guilhabreu", "Junqueira", "Labruge", "Macieira", "Malta", "Mindelo", "Modivas", "Mosteiró", "Outeiro Maior", "Parada", "Retorta", "Rio Mau", "Tougues", "Touguinha", "Touguinhó", "Vairão", "Vila Chã", "Vila do Conde", "Vilar", "Vilar de Pinheiro"],
  "Póvoa de Varzim": ["Aguçadoura", "Amorim", "Argivai", "Balasar", "Beiriz", "Estela", "Laúndos", "Navais", "Póvoa de Varzim", "Rates", "Terroso"],

  // Adicione mais municípios conforme necessário
};

export const TIPOS_IMOVEL = [
  { value: "moradia", label: "Moradia" },
  { value: "apartamento", label: "Apartamento" },
  { value: "casa", label: "Casa" },
  { value: "terreno", label: "Terreno" },
  { value: "escritorio", label: "Escritório" },
  { value: "comercial", label: "Comercial" },
  { value: "industrial", label: "Industrial" },
  { value: "armazem", label: "Armazém" },
  { value: "loja", label: "Loja" },
  { value: "garagem", label: "Garagem" },
  { value: "quinta", label: "Quinta" },
  { value: "terreno_urbano", label: "Terreno Urbano" },
  { value: "terreno_rustico", label: "Terreno Rústico" },
];
