export const DISTRITOS = [
  "Aveiro",
  "Beja",
  "Braga",
  "Bragança",
  "Castelo Branco",
  "Coimbra",
  "Évora",
  "Faro",
  "Guarda",
  "Leiria",
  "Lisboa",
  "Portalegre",
  "Porto",
  "Santarém",
  "Setúbal",
  "Viana do Castelo",
  "Vila Real",
  "Viseu",
];

export const DISTRITO_MUNICIPIOS: { [key: string]: string[] } = {
  Aveiro: [
    "Águeda",
    "Albergaria-a-Velha",
    "Anadia",
    "Arouca",
    "Aveiro",
    "Castelo de Paiva",
    "Espinho",
    "Estarreja",
    "Ílhavo",
    "Mealhada",
    "Murtosa",
    "Oliveira de Azeméis",
    "Oliveira do Bairro",
    "Ovar",
    "Santa Maria da Feira",
    "São João da Madeira",
    "Sever do Vouga",
    "Vagos",
    "Vale de Cambra",
  ],
  Beja: [
    "Aljustrel",
    "Almodôvar",
    "Alvito",
    "Barrancos",
    "Beja",
    "Castro Verde",
    "Cuba",
    "Ferreira do Alentejo",
    "Mértola",
    "Moura",
    "Odemira",
    "Ourique",
    "Serpa",
    "Vidigueira",
  ],
  Braga: [
    "Amares",
    "Barcelos",
    "Braga",
    "Cabeceiras de Basto",
    "Celorico de Basto",
    "Esposende",
    "Fafe",
    "Guimarães",
    "Póvoa de Lanhoso",
    "Terras de Bouro",
    "Vieira do Minho",
    "Vila Nova de Famalicão",
    "Vila Verde",
    "Vizela",
  ],
  Bragança: [
    "Alfândega da Fé",
    "Bragança",
    "Carrazeda de Ansiães",
    "Freixo de Espada à Cinta",
    "Macedo de Cavaleiros",
    "Miranda do Douro",
    "Mirandela",
    "Mogadouro",
    "Torre de Moncorvo",
    "Vila Flor",
    "Vimioso",
    "Vinhais",
  ],
  "Castelo Branco": [
    "Belmonte",
    "Castelo Branco",
    "Covilhã",
    "Fundão",
    "Idanha-a-Nova",
    "Oleiros",
    "Penamacor",
    "Proença-a-Nova",
    "Sertã",
    "Vila de Rei",
    "Vila Velha de Ródão",
  ],
  Coimbra: [
    "Arganil",
    "Cantanhede",
    "Coimbra",
    "Condeixa-a-Nova",
    "Figueira da Foz",
    "Góis",
    "Lousã",
    "Mira",
    "Miranda do Corvo",
    "Montemor-o-Velho",
    "Oliveira do Hospital",
    "Pampilhosa da Serra",
    "Penacova",
    "Penela",
    "Soure",
    "Tábua",
    "Vila Nova de Poiares",
  ],
  Évora: [
    "Alandroal",
    "Arraiolos",
    "Borba",
    "Estremoz",
    "Évora",
    "Montemor-o-Novo",
    "Mora",
    "Mourão",
    "Portel",
    "Redondo",
    "Reguengos de Monsaraz",
    "Vendas Novas",
    "Viana do Alentejo",
    "Vila Viçosa",
  ],
  Faro: [
    "Albufeira",
    "Alcoutim",
    "Aljezur",
    "Castro Marim",
    "Faro",
    "Lagoa",
    "Lagos",
    "Loulé",
    "Monchique",
    "Olhão",
    "Portimão",
    "São Brás de Alportel",
    "Silves",
    "Tavira",
    "Vila do Bispo",
    "Vila Real de Santo António",
  ],
  Guarda: [
    "Aguiar da Beira",
    "Almeida",
    "Celorico da Beira",
    "Figueira de Castelo Rodrigo",
    "Fornos de Algodres",
    "Gouveia",
    "Guarda",
    "Manteigas",
    "Mêda",
    "Pinhel",
    "Sabugal",
    "Seia",
    "Trancoso",
    "Vila Nova de Foz Côa",
  ],
  Leiria: [
    "Alcobaça",
    "Alvaiázere",
    "Ansião",
    "Batalha",
    "Caldas da Rainha",
    "Castanheira de Pera",
    "Figueiró dos Vinhos",
    "Leiria",
    "Marinha Grande",
    "Nazaré",
    "Óbidos",
    "Pedrógão Grande",
    "Peniche",
    "Pombal",
    "Porto de Mós",
  ],
  Lisboa: [
    "Alenquer",
    "Amadora",
    "Arruda dos Vinhos",
    "Azambuja",
    "Bombarral",
    "Cadaval",
    "Cascais",
    "Lisboa",
    "Loures",
    "Lourinhã",
    "Mafra",
    "Odivelas",
    "Oeiras",
    "Sintra",
    "Sobral de Monte Agraço",
    "Torres Vedras",
    "Vila Franca de Xira",
  ],
  Portalegre: [
    "Alter do Chão",
    "Arronches",
    "Avis",
    "Campo Maior",
    "Castelo de Vide",
    "Crato",
    "Elvas",
    "Fronteira",
    "Gavião",
    "Marvão",
    "Monforte",
    "Nisa",
    "Portalegre",
  ],
  Porto: [
    "Amarante",
    "Baião",
    "Felgueiras",
    "Gondomar",
    "Lousada",
    "Maia",
    "Marco de Canaveses",
    "Matosinhos",
    "Paços de Ferreira",
    "Paredes",
    "Penafiel",
    "Porto",
    "Póvoa de Varzim",
    "Santo Tirso",
    "Trofa",
    "Valongo",
    "Vila do Conde",
    "Vila Nova de Gaia",
  ],
  Santarém: [
    "Abrantes",
    "Alcanena",
    "Almeirim",
    "Benavente",
    "Cartaxo",
    "Chamusca",
    "Constância",
    "Coruche",
    "Entroncamento",
    "Ferreira do Zêzere",
    "Golegã",
    "Mação",
    "Ourém",
    "Rio Maior",
    "Salvaterra de Magos",
    "Santarém",
    "Sardoal",
    "Tomar",
    "Torres Novas",
  ],
  Setúbal: [
    "Alcácer do Sal",
    "Alcochete",
    "Almada",
    "Barreiro",
    "Grândola",
    "Moita",
    "Montijo",
    "Palmela",
    "Santiago do Cacém",
    "Seixal",
    "Setúbal",
    "Sesimbra",
    "Sines",
  ],
  "Viana do Castelo": [
    "Arcos de Valdevez",
    "Caminha",
    "Melgaço",
    "Monção",
    "Paredes de Coura",
    "Ponte da Barca",
    "Ponte de Lima",
    "Valença",
    "Viana do Castelo",
    "Vila Nova de Cerveira",
  ],
  "Vila Real": [
    "Alijó",
    "Boticas",
    "Chaves",
    "Mesão Frio",
    "Mondim de Basto",
    "Montalegre",
    "Peso da Régua",
    "Ribeira de Pena",
    "Sabrosa",
    "Santa Marta de Penaguião",
    "Valpaços",
    "Vila Pouca de Aguiar",
    "Vila Real",
  ],
  Viseu: [
    "Armamar",
    "Carregal do Sal",
    "Castro Daire",
    "Cinfães",
    "Lamego",
    "Mangualde",
    "Moimenta da Beira",
    "Nelas",
    "Oliveira de Frades",
    "Penalva do Castelo",
    "Penedono",
    "Resende",
    "Santa Comba Dão",
    "São João da Pesqueira",
    "Sátão",
    "Tondela",
    "Vila Nova de Paiva",
    "Viseu",
  ],
};

export const MUNICIPIO_FREGUESIAS: { [key: string]: string[] } = {
  // ==================== AVEIRO ====================
  "Águeda": ["Águeda e Borralha", "Aguada de Cima", "Barrô e Aguada de Baixo", "Belazaima do Chão, Castanheira do Vouga e Agadão", "Fermentelos", "Macinhata do Vouga", "Préstimo e Macieira de Alcoba", "Recardães e Espinhel", "Travassô e Óis da Ribeira", "Trofa, Segadães e Lamas do Vouga", "Valongo do Vouga"],
  "Albergaria-a-Velha": ["Albergaria-a-Velha e Valmaior", "Alquerubim", "Angeja", "Branca", "Ribeira de Fráguas", "São João de Loure e Frossos"],
  "Anadia": ["Amoreira da Gândara e Paredes do Bairro", "Ancas", "Arcos", "Avelãs de Caminho", "Avelãs de Cima", "Moita", "Mogofores", "Sangalhos", "São Lourenço do Bairro", "Tamengos, Aguim e Óis do Bairro", "Vila Nova de Monsarros", "Vilarinho do Bairro"],
  "Arouca": ["Alvarenga", "Arouca e Burgo", "Cabreiros e Albergaria da Serra", "Canelas e Espiunca", "Chave", "Covelo de Paivó", "Escariz", "Fermedo", "Janarde", "Mansores", "Moldes", "Rossas", "Santa Eulália", "São Miguel do Mato", "Tropeço", "Urrô", "Várzea"],
  "Aveiro": ["Aradas", "Cacia", "Eixo e Eirol", "Esgueira", "Glória e Vera Cruz", "Oliveirinha", "Requeixo, Nossa Senhora de Fátima e Nariz", "Santa Joana", "São Bernardo", "São Jacinto"],
  "Castelo de Paiva": ["Bairros", "Fornos", "Paraíso", "Pedorido", "Raiva", "Real", "Santa Maria de Sardoura", "São Martinho de Sardoura", "Sobrado"],
  "Espinho": ["Anta e Guetim", "Espinho", "Paramos", "Silvalde"],
  "Estarreja": ["Avanca", "Beduído e Veiros", "Canelas e Fermelã", "Pardilhó", "Salreu"],
  "Ílhavo": ["Gafanha da Encarnação", "Gafanha da Nazaré", "Gafanha do Carmo", "Ílhavo (São Salvador)"],
  "Mealhada": ["Barcouço", "Casal Comba", "Luso", "Mealhada, Ventosa do Bairro e Antes", "Pampilhosa", "Vacariça"],
  "Murtosa": ["Bunheiro", "Monte", "Murtosa", "Torreira"],
  "Oliveira de Azeméis": ["Carregosa", "César", "Fajões", "Loureiro, Pinheiro da Bemposta e Travanca", "Macieira de Sarnes e Nogueira do Cravo", "Madail", "Oliveira de Azeméis, Santiago de Riba-Ul, Ul, Macinhata da Seixa e Madail", "Ossela", "Palmaz", "Pindelo", "São Martinho da Gândara", "São Roque", "Vila de Cucujães"],
  "Oliveira do Bairro": ["Bustos, Troviscal e Mamarrosa", "Oiã", "Oliveira do Bairro", "Palhaça"],
  "Ovar": ["Arada", "Cortegaça", "Esmoriz", "Maceda", "Ovar, São João, Arada e São Vicente de Pereira Jusã", "Válega"],
  "Santa Maria da Feira": ["Argoncilhe", "Arrifana", "Caldas de São Jorge e Pigeiros", "Canedo, Vale e Vila Maior", "Escapães", "Fiães", "Fornos", "Lobão, Gião, Louredo e Guisande", "Lourosa", "Milheirós de Poiares", "Mozelos", "Nogueira da Regedoura", "Paços de Brandão", "Rio Meão", "Romariz", "Sanfins, Lamelas e Lamas", "Santa Maria da Feira, Travanca, Sancho e Espargo", "Santa Maria de Lamas", "São João de Ver", "São Paio de Oleiros", "Sanguedo"],
  "São João da Madeira": ["São João da Madeira"],
  "Sever do Vouga": ["Cedrim e Paradela", "Couto de Esteves", "Pessegueiro do Vouga", "Rocas do Vouga", "Sever do Vouga", "Silva Escura e Dornelas", "Talhadas"],
  "Vagos": ["Calvão", "Covão do Lobo, Ponte de Vagos e Santa Catarina", "Fonte de Angeão e Gafanha da Boa Hora", "Ouca e Sosa", "Santo André de Vagos", "Santo António de Vagos", "Vagos"],
  "Vale de Cambra": ["Arões e Lordelo", "Cepelos e Gatão", "Codal e Vila Chã", "Junqueira", "Macieira de Cambra e Rôge", "São Pedro de Castelões", "Vila Cova de Perrinho e Vila Cova da Lixa"],

  // ==================== BEJA ====================
  "Aljustrel": ["Aljustrel", "Ervidel", "Messejana", "Rio de Moinhos", "São João de Negrilhos"],
  "Almodôvar": ["Aldeia dos Fernandes", "Almodôvar e Graça dos Padrões", "Rosário", "Santa Clara-a-Nova e Gomes Aires", "Santa Cruz", "São Barnabé"],
  "Alvito": ["Alvito", "Vila Nova da Baronia"],
  "Barrancos": ["Barrancos"],
  "Beja": ["Albernoa e Trindade", "Baleizão", "Beja (Salvador e Santa Maria da Feira)", "Beja (Santiago Maior e São João Baptista)", "Beringel", "Cabeça Gorda", "Mombeja e Trigaches", "Nossa Senhora das Neves", "Salvada e Quintos", "Santa Clara de Louredo", "Santa Vitória e Mombeja", "São Brissos", "São Matias"],
  "Castro Verde": ["Casével", "Castro Verde e Casével", "Entradas", "Santa Bárbara de Padrões"],
  "Cuba": ["Cuba", "Faro do Alentejo", "Vila Alva", "Vila Ruiva"],
  "Ferreira do Alentejo": ["Alfundão e Peroguarda", "Canhestros", "Ferreira do Alentejo", "Figueira dos Cavaleiros", "Odivelas"],
  "Mértola": ["Alcaria Ruiva", "Corte do Pinto", "Espírito Santo", "Mértola", "Santana de Cambas", "São João dos Caldeireiros", "São Miguel do Pinheiro, São Pedro de Solis e São Sebastião dos Carros"],
  "Moura": ["Amareleja", "Moura (Santo Agostinho e São João Baptista) e Santo Amador", "Póvoa de São Miguel", "Safara e Santo Aleixo da Restauração", "Sobral da Adiça"],
  "Odemira": ["Boavista dos Pinheiros", "Colos", "Longueira/Almograve", "Luzianes-Gare", "Relíquias", "Sabóia", "Santa Clara-a-Velha", "São Luís", "São Martinho das Amoreiras", "São Salvador e Santa Maria", "São Teotónio", "Vale de Santiago", "Vila Nova de Milfontes"],
  "Ourique": ["Garvão e Santa Luzia", "Ourique", "Panoias e Conceição", "Santana da Serra"],
  "Serpa": ["Brinches", "Pias", "Serpa (Salvador e Santa Maria)", "Vila Nova de São Bento e Vale de Vargo", "Vila Verde de Ficalho"],
  "Vidigueira": ["Pedrógão", "Selmes", "Vidigueira", "Vila de Frades"],

  // ==================== BRAGA ====================
  "Amares": ["Amares e Figueiredo", "Barreiros", "Besteiros e Lago", "Bouro (Santa Maria) e Bouro (Santa Marta)", "Caldelas, Sequeiros e Paranhos", "Carrazedo", "Caires e Ferreiros", "Dornelas", "Fiscal", "Goães", "Paredes Secas e Torre", "Prozelo", "Rendufe", "Vilela, Seramil e Paredes Secas"],
  "Barcelos": ["Aborim", "Adães", "Aguiar", "Airó", "Aldreu", "Alheira", "Alvelos", "Arcozelo", "Areias", "Areias de Vilar", "Balugães", "Barcelinhos", "Barcelos, Vila Boa e Vila Frescaínha (São Martinho e São Pedro)", "Barqueiros", "Campo e Tamel (São Pedro Fins)", "Carapeços", "Carreira", "Carvalhal", "Carvalhos", "Chavão", "Chorente, Góios, Courel, Pedra Furada e Gueral", "Cossourado", "Couto", "Creixomil", "Cristelo", "Durrães e Tregosa", "Encourados", "Faria", "Feitos", "Fornelos", "Fragoso", "Gamil", "Gilmonde", "Grimancelos", "Igreja Nova", "Lama", "Lijó", "Macieira de Rates", "Manhente", "Martim", "Midões", "Milhazes, Vilar de Figos e Faria", "Minhonote", "Monte de Fralães", "Moure", "Negreiros", "Oliveira", "Palme", "Panque", "Paradela", "Pereira", "Perelhal", "Pousa", "Quintiães", "Remelhe", "Rio Covo (Santa Eugénia)", "Rio Covo (Santa Eulália)", "Roriz", "Sequeade", "Silva", "Silveiros e Rio Covo (Santa Eulália)", "Tamel (Santa Leocádia) e Vilar do Monte", "Tregosa", "Ucha", "Várzea", "Viatodos, Grimancelos, Minhotães e Monte de Fralães", "Vila Cova e Feitos", "Vila Seca", "Vilar de Figos"],
  "Braga": ["Adaúfe", "Arentim e Cunha", "Braga (Maximinos, Sé e Cividade)", "Braga (São José de São Lázaro e São João do Souto)", "Braga (São Vicente)", "Cabreiros e Passos (São Julião)", "Celeirós, Aveleda e Vimieiro", "Crespos e Pousada", "Cunha", "Escudeiros e Penso (Santo Estêvão e São Vicente)", "Espinho, Sobreposta e Nogueira", "Este (São Mamede e São Pedro)", "Esporões", "Figueiredo", "Fraião e Nogueiró", "Fradelos", "Gondizalves", "Gualtar", "Guisande e Oliveira (São Pedro)", "Lamas e Navarra", "Lomar e Arcos", "Mire de Tibães", "Morreira e Trandeiras", "Merelim (São Paio), Panoias e Parada de Tibães", "Merelim (São Pedro) e Frossos", "Padim da Graça", "Palmeira", "Pedralva", "Priscos", "Real, Dume e Semelhe", "Ruilhe", "Santa Lucrécia de Algeriz e Navarra", "São Vítor", "Sequeira e Tenões", "Sobreposta", "Tadim", "Tebosa", "Vila Verde e Barbudo", "Vilaça e Fradelos"],
  "Cabeceiras de Basto": ["Abadim", "Alvite", "Arco de Baúlhe e Vila Nune", "Basto", "Cabeceiras de Basto", "Cavez", "Faia", "Gondiães e Vilar de Cunhas", "Painzela", "Passos", "Pedraça", "Refojos de Basto, Outeiro e Painzela", "Rio Douro", "Vila Nune"],
  "Celorico de Basto": ["Arnoia", "Basto (São Clemente)", "Borba da Montanha", "Britelo, Gémeos e Ourilhe", "Caçarilhe", "Canedo de Basto", "Carvalho e Basto (Santa Tecla)", "Codeçoso", "Corgo", "Fervença", "Gagos e Molares", "Gémeos", "Infesta", "Moreira do Castelo", "Rego", "Ribas", "Vale de Bouro"],
  "Esposende": ["Antas e Abade de Neiva", "Apúlia e Fão", "Belinho e Mar", "Esposende, Marinhas e Gandra", "Fonte Boa e Rio Tinto", "Forjães", "Gemeses", "Palmeira de Faro e Curvos"],
  "Fafe": ["Aboim, Felgueiras, Gontim e Pedraído", "Agrela e Serafão", "Antime e Silvares (São Clemente)", "Ardegão, Arnozela e Seidões", "Armil", "Arões (Santa Cristina) e Arões (São Romão)", "Cepães e Fareja", "Estorãos e Monte", "Fafe", "Fornelos e Queimadela", "Freitas e Vila Cova", "Golães", "Medelo e Quinchães", "Moreira de Rei e Várzea Cova", "Passos e Gontim", "Revelhe", "Ribeiros e São Gens", "Silvares (São Martinho) e Travassós", "Vinhós"],
  "Guimarães": ["Abação e Gémeos", "Airão (Santa Maria), Airão (São João) e Vermil", "Aldão", "Atães e Rendufe", "Azurém", "Barco", "Brito", "Briteiros (Santo Estêvão) e Donim", "Briteiros (São Salvador) e Briteiros (Santa Leocádia)", "Caldelas", "Candoso (São Tiago) e Mascotelos", "Conde e Gandarela", "Costa", "Creixomil", "Fermentões", "Gonça", "Gondar", "Guardizela", "Infantas", "Leitões, Oleiros e Figueiredo", "Lordelo", "Mesão Frio", "Moreira de Cónegos", "Nespereira", "Pencelo", "Pinheiro", "Polvoreira", "Ponte", "Prazins (Santa Eufémia) e Corvite", "Prazins (Santo Tirso) e Sande (São Lourenço)", "Ronfe", "Sande (São Martinho)", "Sande (Vila Nova) e Sande (São Clemente)", "São Torcato", "Selho (São Cristóvão) e Selho (São Jorge)", "Selho (São Lourenço) e Gominhães", "Serzedelo", "Serzedo e Calvos", "Silvares", "Souto (Santa Maria) e Souto (São Salvador)", "Tabuadelo e São Faustino", "Urgezes", "União das freguesias de Oliveira, São Paio e São Sebastião", "Guimarães"],
  "Póvoa de Lanhoso": ["Águas Santas e Moure", "Brunhais", "Calvos e Frades", "Campo e Taíde", "Covelas e Fonte Arcada", "Esperança e Brunhais", "Ferreiros e Gondizalves", "Fontarcada", "Friande e Paradela", "Garfe", "Geraz do Minho", "Lanhoso", "Monsul e Sobradelo", "Oliveira", "Póvoa de Lanhoso", "Rendufinho", "São João de Rei", "Serzedelo", "Travassos", "Verim e Frades"],
  "Terras de Bouro": ["Balança", "Campo do Gerês", "Chamoim e Vilar", "Chorense e Monte", "Cibões", "Covide", "Gondoriz", "Moimenta", "Monte e Queimadela", "Rio Caldo", "Ribeira e Souto", "Valdozende e Vilar da Veiga"],
  "Vieira do Minho": ["Anissó e Soutelo", "Anjos e Vilar do Chão", "Cantelães", "Caniçada e Soengas", "Eira Vedra", "Guilhofrei", "Louredo", "Mosteiro e Pinheiro", "Parada do Bouro", "Rossas e Anissó", "Ruivães e Campos", "Salamonde", "Tabuaças", "Ventosa e Cova", "Vieira do Minho"],
  "Vila Nova de Famalicão": ["Antas e Abade de Vermoim", "Arnoso (Santa Maria) e Arnoso (Santa Eulália)", "Avidos e Lagoa", "Bairro", "Calendário, Vale (São Cosme) e Gavião", "Carreira e Bente", "Castelões e Landim", "Cavalões", "Cruz e Esmeriz", "Delães", "Fradelos", "Gavião", "Gondifelos, Cavalões e Outiz", "Jesufrei e Rio Covo", "Joane", "Lemenhe, Mouquim e Jesufrei", "Louro", "Lousado", "Nine", "Novais e Seide (São Miguel)", "Oliveira (Santa Maria)", "Oliveira (São Mateus)", "Pedome e Riba de Ave", "Pousada de Saramagos", "Requião", "Ribeirão", "Ruivães", "Vale (São Martinho) e Curvos", "Vermoim", "Vila Nova de Famalicão"],
  "Vila Verde": ["Aboim da Nóbrega e Gondomar", "Atiães", "Barbudo e Vila de Prado", "Cabanelas e Loureira", "Cervães", "Coucieiro e Arcozelo", "Dossãos e Sande", "Esqueiros, Nevogilde e Travassós", "Freiriz", "Gême e Turiz", "Goães", "Gondizalves", "Lanhas", "Lage", "Marrancos e Arcozelo", "Moure e Ribeira do Neiva", "Oleiros", "Oriz (Santa Marinha) e Oriz (São Miguel)", "Parada de Gatim", "Passô e Valbom (São Martinho)", "Pedregais", "Pico", "Pico de Regalados, Gondiães e Mós", "Prado (São Miguel), Prado (Santa Maria) e Ajude", "Rio Mau e Arcos", "Sabariz e Moure", "Sande e São Lourenço de Sande", "Soutelo e Seara", "Travassós", "Turiz e Esporões", "Valbom (São Pedro) e Passô", "Vila Verde e Barbudo", "Vilarinho"],
  "Vizela": ["Infias", "Caldas de Vizela (São Miguel) e Caldas de Vizela (São João)", "Santa Eulália", "Santo Adrião de Vizela", "Tagilde e Vizela (São Paio)", "Vizela (Santo Adrião)"],

  // ==================== BRAGANÇA ====================
  "Alfândega da Fé": ["Alfândega da Fé", "Cerejais", "Eucísia, Gouveia e Valverde", "Ferradosa", "Gebelim e Soeima", "Parada", "Pombal e Vales", "Sambade", "Sendim da Serra e Sendim da Ribeira", "Vilares da Vilariça e Agrobom", "Vilarelhos e Estevais"],
  "Bragança": ["Alfaião", "Aveleda e Rio de Onor", "Babe", "Bragança", "Calvelhe", "Carragosa", "Carrazedo e Refoios", "Castanheira e Donai", "Castro de Avelãs", "Coelhoso", "Deilão e Parada", "Espinhosela", "Faílde e Gondesende", "Gostei", "Freixedelo", "Gimonde", "Grijó de Parada e Parada de Infanções", "Izeda, Calvelhe e Paradinha Nova", "Macedo do Mato e Salselas", "Meixedo e Padornelos", "Milhão", "Mós e Freixeda", "Nogueira e Soeira", "Outeiro e Rio Frio", "Paredes e Quintela", "Pinela", "Quintanilha", "Rabal", "Rebordãos", "Rio de Onor", "Salsas", "Samil", "São Julião de Palácios e Deilão", "São Pedro de Sarracenos", "Sendas e Castro de Avelãs", "Sortes", "Zoio"],
  "Carrazeda de Ansiães": ["Amedo e Zedes", "Belver e Mogo de Malta", "Carrazeda de Ansiães", "Castanheiro e Parambos", "Fontelonga e Beira Grande", "Lavandeira e Pinhal do Norte", "Linhares", "Pereiros", "Pombal de Ansiães", "Ribalonga e Seixo de Ansiães", "Selores e Marzagão", "Vilarinho da Castanheira"],
  "Freixo de Espada à Cinta": ["Fornos", "Freixo de Espada à Cinta e Mazouco", "Lagoaça e Poiares", "Ligares"],
  "Macedo de Cavaleiros": ["Amendoeira", "Arcas e Ala", "Bagueixe", "Bornes e Burga", "Carrapatas, Cortiços e Soutelo Mourisco", "Castelãos", "Chacim e Grijó de Vale Benfeito", "Corujas", "Espadanedo, Edroso e Murçós", "Ferreira e Sezulfe", "Grijó de Parada e Parada", "Lamalonga e Lamas", "Macedo de Cavaleiros", "Malta e Podence", "Morais", "Olmos e Lagoa", "Peredo, Castro e Urrós", "Talhas", "Talhinhas", "Vale da Porca e Santa Combinha", "Vale de Prados e Vale de Telhas", "Vilar do Monte e Vinhas", "Vilarinho de Agrochão"],
  "Miranda do Douro": ["Águas Vivas", "Cicouro, Cércio e São Martinho de Angueira", "Constantim e Cicouro", "Duas Igrejas", "Genísio", "Ifanes e Paradela", "Malhadas", "Miranda do Douro", "Palaçoulo", "Picote", "Póvoa", "São Martinho de Angueira", "Sendim e Atenor", "Silva e Águas Vivas", "Teixeira e Vila Chã da Braciosa", "Vila Chã de Braciosa"],
  "Mirandela": ["Abambres, Cabanelas e Torre de Dona Chama", "Avantos e Romeu", "Barcel, Marmelos e Avidagos", "Bouça e Passos", "Caravelas e Aguieiras", "Cedães e Múrias", "Cobro, Avantos e Valongo de Milhais", "Franco e Valverde da Gestosa", "Freixeda, Lamas de Orelhão e Vale de Couço", "Frechas e Mascarenhas", "Mirandela", "São Pedro Velho e Vile", "São Salvador e Vale de Asnes", "Suçães e Vale de Gouvinhas", "Vilar de Ledra e Pereira", "Vilas Boas"],
  "Mogadouro": ["Azinhoso e Urrós", "Bemposta", "Bruçó e Tó", "Brunhosinho, Castanheira e Soutelo", "Castelo Branco e Vilar de Rei", "Castro Vicente e São Martinho do Peso", "Meirinhos e Paradela", "Mogadouro, Valverde, Vale de Porco e Vilar de Rei", "Penas Roias", "Peredo da Bemposta e Travanca", "Remondes e Saldanha", "Sanhoane e Zava", "Urrós", "Ventozelo", "Vila de Ala e Vilarinho dos Galegos"],
  "Torre de Moncorvo": ["Açoreira", "Adeganha", "Carviçais", "Castedo e Horta da Vilariça", "Felgar", "Felgueiras e Maçores", "Larinho", "Lousa", "Mós e Cabeça Boa", "Souto da Velha", "Torre de Moncorvo", "Urros"],
  "Vila Flor": ["Benlhevai e Samões", "Candoso e Carvalho de Egas", "Freixiel", "Lodões e Roios", "Nabo e Valtorno", "Santa Comba de Vilariça", "Seixo de Manhoses", "Trindade e Vilarinho das Azenhas", "Vila Flor", "Vilas Boas e Vilarinho da Castanheira"],
  "Vimioso": ["Algoso e Campo de Víboras", "Argozelo", "Caçarelhos", "Matela", "Pinelo e Avelanoso", "Santulhão e Vimioso", "Uva e Carção", "Vale de Frades e Vilar Seco"],
  "Vinhais": ["Agrochão e Candedo", "Celas e Pinheiro Novo", "Ervedosa e Rebordelo", "Fresulfe, Vila Boa de Ousilhão e Vilar de Ossos", "Moimenta e Montouto", "Nunes e Ousilhão", "Paçó e Sobreiro de Baixo", "Penhas Juntas e Pinheiro Velho", "Quirás", "Rebordainhos e Curopos", "Santalha e Penhas Juntas", "Soeira e Rio de Fornos", "Travanca e Vila Verde", "Tuizelo e Vinhais", "Vale de Janeiro e Vilar de Lomba", "Vale das Fontes e Vilar de Peregrinos", "Vilar Seco e Edral"],

  // ==================== CASTELO BRANCO ====================
  "Belmonte": ["Belmonte e Colmeal da Torre", "Caria", "Inguias", "Maçainhas"],
  "Castelo Branco": ["Alcains", "Almaceda", "Benquerenças", "Castelo Branco", "Cebolais de Cima e Retaxo", "Escalos de Baixo e Mata", "Escalos de Cima e Lousa", "Freixial e Juncal do Campo", "Lardosa", "Louriçal do Campo", "Malpica do Tejo", "Monforte da Beira", "Ninho do Açor e Sobral do Campo", "Póvoa de Rio de Moinhos e Cafede", "Salgueiro do Campo", "São Vicente da Beira", "Sarzedas", "Tinalhas"],
  "Covilhã": ["Aldeia de São Francisco de Assis", "Barco e Coutada", "Boidobra", "Cantar-Galo e Vila do Carvalho", "Cortes do Meio", "Coutada e Boidobra", "Covilhã", "Dominguiso", "Erada e Atalaia do Campo", "Ferro", "Orjais e Casegas", "Ourondo e Verdelhos", "Paul", "Peraboa", "Sarzedo e Rebordinho", "Sobral de São Miguel", "Teixoso e Sarzedo", "Tortosendo", "Unhais da Serra", "Vale Formoso e Aldeia do Souto", "Vales do Rio e Unhais-o-Velho", "Verdelhos"],
  "Fundão": ["Alcaide", "Alcaria", "Alcongosta", "Alpedrinha", "Atalaia do Campo", "Barroca", "Bogas de Cima", "Capinha", "Castelejo", "Castelo Novo", "Donas, Aldeia de Joanes e Aldeia Nova do Cabo", "Enxames", "Fatela", "Fundão, Valverde, Donas e Aldeia de Joanes", "Janeiro de Cima", "Lavacolhos", "Mata da Rainha", "Orca e Teixugueira", "Pêro Viseu", "Salgueiro", "Silvares", "Soalheira", "Souto da Casa", "Telhado", "Vale de Prazeres e Mata da Rainha", "Valverde"],
  "Idanha-a-Nova": ["Aldeia de Santa Margarida", "Idanha-a-Nova", "Ladoeiro", "Medelim", "Monsanto e Idanha-a-Velha", "Monfortinho e Salvaterra do Extremo", "Oledo", "Penha Garcia", "Proença-a-Velha", "Rosmaninhal", "São Miguel de Acha e Toulões", "Segura", "Zebreira e Segura"],
  "Oleiros": ["Álvaro", "Cambas e Madeirã", "Estreito, Vilar Barroco e Sarnadas de São Simão", "Isna e Roqueiro", "Mosteiro", "Oleiros e Amieira", "Orvalho", "Sobral e Sarzedas", "Vilar Barroco"],
  "Penamacor": ["Aldeia de João Pires", "Aldeia do Bispo, Águas e Aranhas", "Bemposta", "Meimão", "Meimoa", "Pedrógão de São Pedro", "Penamacor", "Salvador e Benquerença", "Vale da Senhora da Póvoa"],
  "Proença-a-Nova": ["Alvito da Beira", "Montes da Senhora", "Proença-a-Nova, Peral, Montes da Senhora e Sobreira Formosa", "São Pedro do Esteval", "Sobreira Formosa"],
  "Sertã": ["Cabeçudo", "Carvalhal e Pedrogão Pequeno", "Castelo", "Cernache do Bonjardim, Nesperal e Palhais", "Cumeada", "Ermida e Figueiredo", "Figueiredo", "Nesperal", "Palhais e Coentral Grande", "Pedrógão Pequeno", "Sertã", "Troviscal"],
  "Vila de Rei": ["Fundada", "São João do Peso", "Vila de Rei e Milreu"],
  "Vila Velha de Ródão": ["Fratel e Perais", "Sarnadas de Ródão", "Vila Velha de Ródão"],

  // ==================== COIMBRA ====================
  "Arganil": ["Arganil", "Benfeita", "Celavisa", "Cepos e Teixeira", "Cerdeira e Moura da Serra", "Coja e Barril de Alva", "Folques", "Piódão", "Pomares", "Pombeiro da Beira", "São Martinho da Cortiça", "Secarias", "Sarzedo e Vila Cova de Alva"],
  "Cantanhede": ["Ançã", "Bolho", "Cadima", "Camarneira e Sepins", "Cantanhede e Pocariça", "Cordinhã", "Covões e Camarneira", "Febres", "Murtede", "Ourentã", "Portunhos e Outil", "Sanguinheira", "São Caetano", "Tocha", "Vilamar e Corticeiro de Cima"],
  "Coimbra": ["Almalaguês e Brasfemes", "Antuzede e Vil de Matos", "Assafarge e Antanhol", "Botão e Souselas", "Ceira e Santo António dos Olivais", "Cernache", "Eiras e São Paulo de Frades", "Ribeira de Frades", "Santa Clara e Castelo Viegas", "São João do Campo", "São Martinho de Árvore e Lamarosa", "São Martinho do Bispo e Ribeira de Frades", "São Silvestre", "Taveiro, Ameal e Arzila", "Torres do Mondego e Trouxemil", "União das Freguesias da Sé Nova, Santa Cruz, Almedina e São Bartolomeu"],
  "Condeixa-a-Nova": ["Anobra", "Belide e Zambujal", "Condeixa-a-Nova e Condeixa-a-Velha", "Ega", "Furadouro", "Sebal e Belide", "Vila Seca e Bem da Fé"],
  "Figueira da Foz": ["Alhadas", "Alqueidão", "Bom Sucesso e São Julião da Figueira da Foz", "Brenha", "Buarcos e São Julião", "Ferreira-a-Nova", "Lavos", "Maiorca", "Marinha das Ondas", "Moinhos da Gândara", "Paião", "Quiaios", "São Pedro", "Tavarede", "Vila Verde"],
  "Góis": ["Alvares", "Cadafaz e Colmeal", "Góis", "Vila Nova do Ceira"],
  "Lousã": ["Casal de Ermio e Serpins", "Foz de Arouce e Casal de Ermio", "Lousã e Vilarinho", "Serpins"],
  "Mira": ["Carapelhos", "Mira e Praia de Mira", "Seixo"],
  "Miranda do Corvo": ["Lamas", "Miranda do Corvo, Rio Vide e Semide", "Vila Nova"],
  "Montemor-o-Velho": ["Abrunheira, Verride e Vila Nova da Barca", "Arazede", "Carapinheira", "Ereira e Avelãs de Caminho", "Gatões e Liceia", "Meãs do Campo", "Montemor-o-Velho e Gatões", "Pereira", "Santo Varão", "Seixo de Gatões", "Tentúgal"],
  "Oliveira do Hospital": ["Aldeia das Dez", "Alvôco das Várzeas e Meruge", "Avô", "Bobadela, Lagares da Beira e Lajeosa", "Ervedal e Vila Franca da Beira", "Lageosa", "Nogueira do Cravo", "Oliveira do Hospital e São Paio de Gramaços", "Penalva de Alva e São Sebastião da Feira", "Santa Ovaia e Vila Pouca da Beira", "São Gião", "Seixo da Beira", "Travanca de Lagos"],
  "Pampilhosa da Serra": ["Cabril e Dornelas do Zêzere", "Janeiro de Baixo", "Pampilhosa da Serra", "Pessegueiro e Fajão", "Portela do Fojo, Machio e Vidual", "Unhais-o-Velho"],
  "Penacova": ["Carvalho", "Farinha Podre", "Figueira de Lorvão e Penacova", "Friúmes e Paradela", "Lorvão", "Oliveira do Mondego e Travanca do Mondego", "São Pedro de Alva e São Paio de Mondego", "Sazes do Lorvão"],
  "Penela": ["Cumeeira", "Espinhal", "Penela e Rabaçal", "Podentes"],
  "Soure": ["Alfarelos", "Brunhós e Figueiró do Campo", "Degracias e Pombalinho", "Gesteira e Samuel", "Granja do Ulmeiro", "Soure e Tapéus", "Vila Nova de Anços e Vinha da Rainha"],
  "Tábua": ["Ázere e Covelo", "Candosa e Carapinha", "Espariz e Sinde", "Midões", "Mouronho", "Pinheiro de Coja e Meda de Mouros", "São João da Boa Vista", "Tábua"],
  "Vila Nova de Poiares": ["Arrifana", "Lavegadas", "Poiares (Santo André)", "São Miguel de Poiares"],

  // ==================== ÉVORA ====================
  "Alandroal": ["Alandroal (Nossa Senhora da Conceição), São Brás dos Matos (Mina do Bugalho) e Juromenha (Nossa Senhora do Loreto)", "Capelins (Santo António)", "Santiago Maior", "Terena (São Pedro)"],
  "Arraiolos": ["Arraiolos", "Igrejinha", "Santa Justa", "São Gregório e Santa Justa", "Sabugueiro", "Vimieiro e Santana do Campo"],
  "Borba": ["Borba (Matriz)", "Borba (São Bartolomeu)", "Orada", "Rio de Moinhos"],
  "Estremoz": ["Arcos e Glória", "Evoramonte (Santa Maria)", "Estremoz (Santa Maria e Santo André)", "São Bento do Cortiço", "São Domingos de Ana Loura e São Lourenço de Mamporcão", "Santo Estêvão e Veiros"],
  "Évora": ["Bacelo e Senhora da Saúde", "Canaviais", "Évora (São Mamede, Sé, São Pedro e Santo Antão)", "Horta das Figueiras", "Malagueira e Nossa Senhora da Graça do Divor", "Nossa Senhora da Tourega e Nossa Senhora de Guadalupe", "Nossa Senhora de Machede", "São Bento do Mato", "São Manços e São Vicente do Pigeiro", "São Miguel de Machede", "São Sebastião da Giesteira e Nossa Senhora da Boa Fé", "Torre de Coelheiros"],
  "Montemor-o-Novo": ["Cabrela", "Ciborro", "Cortiçadas de Lavre e Lavre", "Foros de Vale Figueira", "Nossa Senhora da Vila, Nossa Senhora do Bispo e Silveiras", "Santiago do Escoural", "São Cristóvão e São Geraldo"],
  "Mora": ["Brotas", "Cabeção", "Mora", "Pavia"],
  "Mourão": ["Granja e Luz", "Mourão"],
  "Portel": ["Amieira", "Monte do Trigo e Portel", "Santana", "São Bartolomeu do Outeiro e Oriola", "Vera Cruz"],
  "Redondo": ["Montoito", "Redondo"],
  "Reguengos de Monsaraz": ["Corval", "Monsaraz", "Reguengos de Monsaraz (Santo António)", "Reguengos de Monsaraz (São Pedro)"],
  "Vendas Novas": ["Vendas Novas e Landeira"],
  "Viana do Alentejo": ["Aguiar", "Alcáçovas", "Viana do Alentejo"],
  "Vila Viçosa": ["Bencatel", "Ciladas", "Pardais", "Vila Viçosa (Conceição) e Vila Viçosa (São Bartolomeu)"],

  // ==================== FARO ====================
  "Albufeira": ["Albufeira e Olhos de Água", "Ferreiras", "Guia", "Paderne"],
  "Alcoutim": ["Alcoutim e Pereiro", "Giões", "Martim Longo", "Vaqueiros"],
  "Aljezur": ["Aljezur", "Bordeira", "Odeceixe", "Rogil"],
  "Castro Marim": ["Altura", "Azinhal, Odeleite e Corte do Gago", "Castro Marim"],
  "Faro": ["Conceição e Estoi", "Faro (São Pedro)", "Faro (Sé e São Pedro)", "Montenegro", "Santa Bárbara de Nexe"],
  "Lagoa": ["Carvoeiro", "Estômbar e Parchal", "Ferragudo", "Lagoa e Porches"],
  "Lagos": ["Bensafrim e Barão de São João", "Lagos (São Sebastião e Santa Maria)", "Luz", "Odiáxere"],
  "Loulé": ["Almancil", "Alte", "Ameixial", "Boliqueime", "Loulé (São Clemente)", "Loulé (São Sebastião)", "Quarteira", "Salir", "União das freguesias de Querença, Tôr e Benafim"],
  "Monchique": ["Alferce", "Marmelete", "Monchique"],
  "Olhão": ["Fuseta", "Moncarapacho e Fuseta", "Olhão", "Pechão", "Quelfes"],
  "Portimão": ["Alvor", "Mexilhoeira Grande", "Portimão"],
  "São Brás de Alportel": ["São Brás de Alportel"],
  "Silves": ["Alcantarilha e Pêra", "Algoz e Tunes", "Armação de Pêra", "São Bartolomeu de Messines", "São Marcos da Serra", "Silves"],
  "Tavira": ["Cabanas de Tavira", "Cachopo", "Conceição e Cabanas de Tavira", "Luz de Tavira e Santo Estêvão", "Santa Catarina da Fonte do Bispo", "Santa Luzia", "Tavira (Santa Maria e Santiago)"],
  "Vila do Bispo": ["Barão de São Miguel", "Budens", "Raposeira", "Sagres", "Vila do Bispo"],
  "Vila Real de Santo António": ["Monte Gordo", "Vila Nova de Cacela", "Vila Real de Santo António"],

  // ==================== GUARDA ====================
  "Aguiar da Beira": ["Aguiar da Beira e Coruche", "Carapito", "Cortiçada e Eirado", "Dornelas e Pena Verde", "Forninhos e Sequeiros", "Pinheiro e Soutelinho", "Souto de Aguiar da Beira"],
  "Almeida": ["Almeida", "Castelo Bom", "Castelo Mendo, Ade, Monteperobolso e Mesquitela", "Freineda", "Freixo, Malhada Sorda e Miuzela", "Junça", "Malpartida e Vale de Coelha", "Nave de Haver", "Peva e Amoreira", "São Pedro de Rio Seco e Mata do Rei", "Vale da Mula", "Vilar Formoso"],
  "Celorico da Beira": ["Açores e Velosa", "Baraçal", "Carrapichana", "Casas do Soeiro e Vale de Azares", "Celorico (São Pedro e Santa Maria) e Vila Boa do Mondego", "Cortiçô da Serra, Vide Entre Vinhas e Salgueirais", "Forno Telheiro", "Lajeosa do Mondego e Rapa", "Linhares", "Maçal do Chão", "Mesquitela", "Minhocal e Prados", "Ratoeira"],
  "Figueira de Castelo Rodrigo": ["Algodres e Vale de Afonsinho", "Almofala", "Castelo Rodrigo", "Cinco Vilas e Reigada", "Escalhão", "Figueira de Castelo Rodrigo", "Freixeda do Torrão, Quintã de Pêro Martins e Penha de Águia", "Mata de Lobos", "Vermiosa", "Vilar de Amargo e Colmeal", "Vilar Torpim"],
  "Fornos de Algodres": ["Algodres, Muxagata e Vila Chã", "Cortiço e Vila Soeiro", "Figueiró da Granja", "Fornos de Algodres, Fuinhas e Juncais", "Infias", "Maceira", "Matança e Queiriz", "Sobral Pichorro e Vinha da Moura"],
  "Gouveia": ["Aldeias", "Arcozelo da Serra", "Cativelos", "Figueiró da Serra", "Folgosinho", "Gouveia", "Melo e Nabais", "Moimenta da Serra", "Nespereira", "Paços da Serra", "Rio Torto", "São Julião", "São Paio", "Vinhó e Vila Cortês da Serra"],
  "Guarda": ["Adão, Aldeia Viçosa e Videmonte", "Aldeia do Bispo, Águas Belas e Pousade", "Arrifana e Codesseiro", "Avelãs da Ribeira e Cavadoude", "Benespera", "Casal de Cinza, Porto da Carne e Famalicão", "Castanheira", "Faia, Gonçalo e Seixo Amarelo", "Fernão Joanes", "Gagos, Maçainhas de Baixo e Albardo", "Gonçalo Bocas", "Guarda", "Jarmelo São Miguel", "Jarmelo São Pedro", "João Antão e Sé", "Maçainhas", "Marmeleiro e Rochoso", "Meios, Panoias de Cima e Pêra do Moço", "Mizarela, Pêro Soares e Vila Soeiro", "Monte Margarida e Galegos", "Pousafoles do Bispo, Pega e Alvendre", "Ramela, Pousafoles do Bispo e Corujeira", "Rocamondo, Vila Franca do Deão e Vila Garcia", "Santana da Azinha e Trinta", "Vale de Estrela", "Vila Cortês do Mondego e Vela", "Vila Fernando", "Vila Franca do Deão"],
  "Manteigas": ["Manteigas (Santa Maria) e Manteigas (São Pedro)", "Sameiro e Vale de Amoreira"],
  "Mêda": ["Aveloso", "Barreira", "Casteição", "Coriscada e Rabaçal", "Longroiva", "Marialva", "Mêda, Outeiro de Gatos e Fonte Longa", "Pai Penela e Vale Flor", "Poço do Canto", "Prova e Casteição", "Ranhados", "Vale do Ladrão e Valflor"],
  "Pinhel": ["Atalaia e Safurdão", "Bouça Cova e Souto", "Cerejo e Valbom", "Cidadelhe e Lamelas", "Ervedosa", "Freixedas", "Gouveias e Lamegal", "Lameiras e Pala", "Manigoto e Sorval", "Pinhel", "Pínzio e Vascoveiro", "Souro Pires, Alverca da Beira e Bouça Cova", "Terras de Massueime e Ervedosa", "Vale do Coelho e Vila Maior", "Valbom e Bogalhal"],
  "Sabugal": ["Aldeia da Ribeira, Vilar Maior e Badamalos", "Aldeia do Bispo e Águas Belas", "Aldeia Velha e Águas Belas", "Alfaiates", "Baraçal e Malcata", "Bendada, Lageosa e Cerdeira", "Casteleiro", "Fóios", "Forcalhos e Lomba", "Lajeosa e Forcalhos", "Nave e Aldeia da Ponte", "Quadrazais", "Quintas de São Bartolomeu e Rebolosa", "Rapoula do Côa", "Rendo e Santo Estêvão", "Ruivós e Pousafoles do Bispo", "Sabugal e Aldeia de Santo António", "Seixo do Côa e Vale Longo", "Sortelha", "Souto", "Vale de Espinho e Águas Belas", "Vila Boa e Rochoso", "Vila do Touro e Quintas", "Vilar Formoso e Bismula"],
  "Seia": ["Alvoco da Serra", "Cabeça e Eiro", "Carragozela e Vila Cova à Coelheira", "Folhadosa e Paranhos da Beira", "Girabolhos, Pinhanços e São Gião", "Loriga", "Lajes, Teixeira e Torroselo", "Sameice e Santa Eulália", "Sandomil e Vide", "Santa Comba", "Santiago, Travancinha e Sabugueiro", "São Romão, Pinhanços e Seia", "Seia", "Torrozelo", "Valezim, Carragozela e Várzea de Meruge", "Vila Cova à Coelheira e Várzea de Meruge"],
  "Trancoso": ["Aldeia Nova e Moimentinha", "Carnicães e Fiães", "Castanheira, Granja e Torres", "Cogula e Peneireiro", "Cótimos e Tamanhos", "Feital e Palhais", "Freches e Reboleiro", "Guilheiro, Tamanhos e Trancoso", "Moreira de Rei e Paipenela", "Pínzio e Souto Maior", "Póvoa do Concelho e Coriscada", "Rio de Mel e Vila Garcia", "Torre do Terrenho, Sebadelhe da Serra e Terrenho", "Trancoso (São Pedro) e Trancoso (Santa Maria)", "Vale do Seixo, Aldeia Nova e Valdujo", "Vila Franca das Naves e Póvoa de Trancoso", "Vilares e Carnicães"],
  "Vila Nova de Foz Côa": ["Almendra", "Castelo Melhor", "Cedovim e Couto do Mosteiro", "Chãs e Touça", "Custóias, Horta e Numão", "Freixo de Numão", "Muxagata", "Santa Comba e Mós", "São Pedro da Veiga e Seixas", "Vila Nova de Foz Côa"],

  // ==================== LEIRIA ====================
  "Alcobaça": ["Alcobaça e Vestiaria", "Alfeizerão", "Aljubarrota", "Bárrio e Cós", "Benedita", "Cela", "Évora de Alcobaça e Turquel", "Maiorga", "Martingança", "Montes e Pataias", "São Martinho do Porto", "Vimeiro e Alcobertas"],
  "Alvaiázere": ["Almoster", "Alvaiázere", "Maçãs de Dona Maria", "Pelmá", "Pussos e Alvaiázere", "Rego da Murta e Pussos"],
  "Ansião": ["Alvorge", "Ansião", "Avelar", "Chão de Couce", "Lagarteira e Santiago da Guarda", "Torre de Vale de Todos e Avelar"],
  "Batalha": ["Batalha", "Golpilheira e Reguengo do Fetal", "São Mamede"],
  "Caldas da Rainha": ["A dos Francos", "Alvorninha", "Caldas da Rainha (Nossa Senhora do Pópulo, Coto e São Gregório)", "Caldas da Rainha (Santo Onofre) e Serra do Bouro", "Carvalhal Benfeito", "Foz do Arelho", "Landal e Nadadouro", "Óbidos e Serra do Bouro", "Santa Catarina e São Bartolomeu dos Galegos", "Tornada e Salir de Matos", "Vidais"],
  "Castanheira de Pera": ["Castanheira de Pera e Coentral", "Pedrogão Pequeno"],
  "Figueiró dos Vinhos": ["Aguda", "Arega e Bairradas", "Campelo e Figueiró dos Vinhos"],
  "Leiria": ["Amor", "Arrabal", "Azóia, Colmeias e Parceiros", "Bajouca, Leiria e Marrazes", "Barosa", "Bidoeira de Cima e Maceira", "Caranguejeira", "Coimbrão", "Cortes", "Leiria, Pousos, Barreira e Cortes", "Maceira", "Marrazes e Barosa", "Memória e Santa Eufémia", "Monte Real e Carvide", "Monte Redondo e Caranguejeira", "Parceiros e Azóia", "Pousos", "Regueira de Pontes", "Santa Catarina da Serra", "Souto da Carpalhosa e Ortigosa"],
  "Marinha Grande": ["Marinha Grande", "Moita e Vieira de Leiria"],
  "Nazaré": ["Famalicão", "Nazaré", "Valado dos Frades"],
  "Óbidos": ["A dos Negros", "Amoreira e Olho Marinho", "Gaeiras", "Óbidos (Santa Maria, São Pedro e Sobral da Lagoa)", "Usseira", "Vau"],
  "Pedrógão Grande": ["Graça, Pedrógão Grande e Vila Facaia"],
  "Peniche": ["Atouguia da Baleia", "Peniche (Ajuda, Conceição e São Pedro)", "Serra d'El-Rei"],
  "Pombal": ["Abiul e Albergaria dos Doze", "Almagreira", "Carnide e Pombal", "Guia", "Ilha e Pelariga", "Louriçal", "Mata Mourisca e Carriço", "Meirinhas", "Pombal", "Redinha", "Santiago de Litém e Litém", "Vermoil e Vila Cã"],
  "Porto de Mós": ["Alqueidão da Serra e Mendiga", "Alvados e Alcaria", "Arrimal e Bezerra", "Calvaria de Cima", "Juncal e Vila Moreira", "Mira de Aire e Minde", "Pedreiras", "Porto de Mós", "São Bento e Serro Ventoso"],

  // ==================== LISBOA ====================
  "Alenquer": ["Abrigada e Cabanas de Torres", "Aldeia Galega da Merceana e Aldeia Gavinha", "Alenquer (Santo Estêvão e Triana)", "Carregado e Cadafais", "Carnota", "Meca e Ventosa", "Ota", "Ribafria e Pereiro de Palhacana", "Vila Verde dos Francos"],
  "Amadora": ["Águas Livres", "Alfragide", "Encosta do Sol", "Falagueira-Venda Nova", "Mina de Água", "Venteira"],
  "Arruda dos Vinhos": ["Arranhó", "Arruda dos Vinhos", "Cardosas", "São Tiago dos Velhos"],
  "Azambuja": ["Alcoentre", "Aveiras de Baixo e Aveiras de Cima", "Azambuja", "Manique do Intendente, Vila Nova de São Pedro e Maçussa", "Vale do Paraíso"],
  "Bombarral": ["Bombarral e Vale Covo", "Carvalhal, Pó e Roliça"],
  "Cadaval": ["Alguber", "Cadaval e Pêro Moniz", "Cercal e Lamas", "Figueiros e Painho", "Vermelha, Vilar e Peral"],
  "Cascais": ["Alcabideche", "Carcavelos e Parede", "Cascais e Estoril", "São Domingos de Rana"],
  "Lisboa": ["Ajuda", "Alcântara", "Alvalade", "Areeiro", "Arroios", "Avenidas Novas", "Beato", "Belém", "Benfica", "Campo de Ourique", "Campolide", "Carnide", "Estrela", "Lumiar", "Marvila", "Misericórdia", "Olivais", "Parque das Nações", "Penha de França", "Santa Clara", "Santa Maria Maior", "Santo António", "São Domingos de Benfica", "São Vicente"],
  "Loures": ["Bucelas", "Camarate, Unhos e Apelação", "Fanhões", "Loures", "Lousa", "Moscavide e Portela", "Sacavém e Prior Velho", "Santa Iria de Azóia, São João da Talha e Bobadela", "Santo Antão e São Julião do Tojal", "Santo António dos Cavaleiros e Frielas"],
  "Lourinhã": ["Lourinhã e Atalaia", "Marteleira e Moledo", "Moita dos Ferreiros e Miragaia", "Reguengo Grande e Santa Bárbara", "Ribamar e São Bartolomeu dos Galegos", "Vimeiro"],
  "Mafra": ["Azueira e Sobral da Abelheira", "Carvoeira e Carmões", "Encarnação", "Ericeira", "Igreja Nova e Cheleiros", "Mafra", "Malveira e São Miguel de Alcainça", "Milharado", "Santo Isidoro", "Venda do Pinheiro e Santo Estêvão das Galés"],
  "Odivelas": ["Caneças", "Famões", "Odivelas", "Pontinha e Famões", "Póvoa de Santo Adrião e Olival Basto", "Ramada e Caneças"],
  "Oeiras": ["Algés, Linda-a-Velha e Cruz Quebrada-Dafundo", "Barcarena", "Carnaxide e Queijas", "Oeiras e São Julião da Barra, Paço de Arcos e Caxias", "Porto Salvo"],
  "Sintra": ["Agualva e Mira-Sintra", "Algueirão-Mem Martins", "Almargem do Bispo, Pêro Pinheiro e Montelavar", "Cacém e São Marcos", "Casal de Cambra", "Colares", "Massamá e Monte Abraão", "Queluz e Belas", "Rio de Mouro", "São João das Lampas e Terrugem", "Sintra (Santa Maria e São Miguel, São Martinho e São Pedro de Penaferrim)"],
  "Sobral de Monte Agraço": ["Santo Quintino", "Sapataria", "Sobral de Monte Agraço"],
  "Torres Vedras": ["A dos Cunhados e Maceira", "Campelos e Outeiro da Cabeça", "Carvoeira e Dois Portos", "Freiria", "Maxial e Monte Redondo", "Ponte do Rol e Ramalhal", "Santa Maria, São Pedro e Matacães", "São Pedro da Cadeira", "Silveira", "Torres Vedras (São Pedro, Santiago, Santa Maria do Castelo e São Miguel) e Matacães", "Turcifal", "Ventosa"],
  "Vila Franca de Xira": ["Alhandra, São João dos Montes e Calhandriz", "Alverca do Ribatejo e Sobralinho", "Castanheira do Ribatejo e Cachoeiras", "Póvoa de Santa Iria e Forte da Casa", "Vialonga", "Vila Franca de Xira"],

  // ==================== PORTALEGRE ====================
  "Alter do Chão": ["Alter do Chão", "Chancelaria", "Cunheira", "Seda"],
  "Arronches": ["Arronches", "Assunção e Esperança", "Mosteiros"],
  "Avis": ["Alcôrrego e Maranhão", "Aldeia Velha e Ervidel", "Avis", "Benavila e Valongo", "Figueira e Barros"],
  "Campo Maior": ["Campo Maior", "Nossa Senhora da Expectação e São João Baptista", "Ouguela"],
  "Castelo de Vide": ["Castelo de Vide", "Nossa Senhora da Graça de Póvoa e Meadas", "Santa Maria da Devesa", "Santiago Maior"],
  "Crato": ["Aldeia da Mata", "Crato e Mártires, Flor da Rosa e Vale do Peso", "Gáfete", "Monte da Pedra e Pisão"],
  "Elvas": ["Alcáçova", "Ajuda, Salvador e Santo Ildefonso", "Assunção, Ajuda, Salvador e Santo Ildefonso", "Barbacena", "Caia e São Pedro", "Santa Eulália", "São Brás e São Lourenço", "São Vicente e Ventosa", "Terrugem e Vila Boim", "Vila Fernando"],
  "Fronteira": ["Cabeço de Vide", "Fronteira", "São Saturnino"],
  "Gavião": ["Belver", "Comenda", "Gavião", "Margem"],
  "Marvão": ["Beirã", "Santo António das Areias e São Salvador da Aramenha", "Santa Maria de Marvão"],
  "Monforte": ["Assumar", "Monforte", "Santo Aleixo e Vaiamonte"],
  "Nisa": ["Alpalhão", "Amieira do Tejo e Montalvão", "Nossa Senhora da Graça e São Simão", "Nisa", "Santana", "Tolosa"],
  "Portalegre": ["Alegrete", "Alagoa", "Carreiras e Ribeira de Nisa", "Fortios e Reguengo", "Portalegre", "São Julião e Urra", "Sé e São Lourenço"],

  // ==================== PORTO ====================
  "Amarante": ["Aboadela, Sanche e Várzea", "Amarante (São Gonçalo), Madalena, Cepelos e Gatão", "Ansiães", "Bustelo, Carneiro e Carvalho de Rei", "Candemil", "Fregim", "Freixo de Cima e de Baixo", "Fridão", "Gondar", "Jazente", "Lomba", "Louredo e Mancelos", "Lufrei", "Olo e Canadelo", "Padronelo e Rebordelo", "Real, Ataíde e Oliveira", "Salvador do Monte", "Telões", "Travanca", "Vila Caiz e Vila Chã do Marão", "Vila Garcia, Aboim e Chapa"],
  "Baião": ["Ancede e Ribadouro", "Baião (Santa Leocádia) e Mesquinhata", "Campelo e Ovil", "Frende e Paços de Gaiolo", "Gesta e Gestaçô", "Grilo e Viariz", "Loivos da Ribeira e Tresouras", "Loivos e Mesquinhata", "Santa Cruz do Douro e São Tomé de Covelas", "Santa Marinha do Zêzere", "Teixeira e Teixeiró", "Valadares e Loivos"],
  "Felgueiras": ["Airães", "Aião e Borba de Godim", "Caramos, Varziela, Moure e Pombeiro de Ribavizela", "Friande", "Idães", "Jugueiros e Lemenhe", "Lagares, Refontoura, Regilde e Sendim", "Lixa", "Lordelo, Vila Cova da Lixa e Borba de Godim", "Margaride (Santa Eulália), Várzea, Lagares, Varziela e Moure", "Pedreira, Rande e Sernande", "Penacova", "Pinheiro e Torrados", "Revinhade", "Santão", "Unhão e Lordelo", "Vila Fria e Vizela (São Jorge)", "Vila Verde"],
  "Gondomar": ["Baguim do Monte e Fânzeres", "Foz do Sousa e Covelo", "Gondomar (São Cosme), Valbom e Jovim", "Lomba e Melres", "Rio Tinto", "São Pedro da Cova"],
  "Lousada": ["Aveleda, Covas e Lousada (São Miguel e Santa Margarida)", "Caíde de Rei e Lousada (Santa Margarida)", "Cernadelo e Lousada (Santa Margarida)", "Cristelos, Boim e Lustosa", "Macieira, Meinedo, Nevogilde e Torno", "Nespereira e Casais", "Ordem e Sousela", "Silvares, Pias, Nogueira e Alvarenga", "Vilar do Torno e Alentém"],
  "Maia": ["Águas Santas", "Castêlo da Maia", "Cidade da Maia", "Folgosa", "Milheirós", "Moreira", "Nogueira e Silva Escura", "Pedrouços", "São Pedro Fins", "Vila Nova da Telha"],
  "Marco de Canaveses": ["Alpendurada, Várzea e Torrão", "Ariz e Carvalho de Rei", "Avessadas e Rosém", "Banho e Carvalhosa", "Bem Viver", "Constance", "Freixo de Cima e de Baixo", "Magrelos e Sande", "Marco", "Maureles e Várzea da Ovelha e Aliviada", "Paredes de Viadores e Manhuncelos", "Penha Longa e Paços de Gaiolo", "Quintela e Vila Boa de Quires", "Rio de Galinhas", "Santo Isidoro e Livração", "Soalhães", "Sobretâmega e Várzea do Douro", "Tabuado", "Torrão e Toutosa", "Tuías", "Vila Boa do Bispo"],
  "Matosinhos": ["Custóias, Leça do Balio e Guifões", "Matosinhos e Leça da Palmeira", "Perafita, Lavra e Santa Cruz do Bispo", "São Mamede de Infesta e Senhora da Hora"],
  "Paços de Ferreira": ["Carvalhosa", "Ferreira", "Figueiró", "Frazão Arreigada", "Meixomil e Seroa", "Paços de Ferreira", "Penamaior", "Raimonda", "Sanfins, Lamoso e Codessos"],
  "Paredes": ["Aguiar de Sousa", "Astromil e Rebordosa", "Baltar", "Beire e Parada de Todeia", "Cete", "Cristelo e Lordelo", "Duas Igrejas", "Gandra e Sobrosa", "Mouriz e Vandoma", "Paredes", "Recarei e Sobreira", "Vilela e Sobrado"],
  "Penafiel": ["Abragão e Paço de Sousa", "Bustelo, Pinheiro e Valpedre", "Cabeça Santa", "Canelas e Ferreira", "Capela, Boelhe e Figueira", "Castelões, Eja e Rio de Moinhos", "Croca, Fonte Arcada e Guilhufe", "Duas Igrejas, Luzim e Vila Cova", "Galegos, Milhundos e Novelas", "Irivo e Lagares", "Oldrões e Peroselo", "Penafiel", "Portela e Rans", "Rio Mau e Sebolido", "São Martinho de Recezinhos e Canelas", "Termas de São Vicente", "Vila Verde e Rio de Moinhos"],
  "Porto": ["Aldoar, Foz do Douro e Nevogilde", "Bonfim", "Campanhã", "Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória", "Lordelo do Ouro e Massarelos", "Paranhos", "Ramalde"],
  "Póvoa de Varzim": ["Aguçadoura e Navais", "Aver-o-Mar, Amorim e Terroso", "Balazar", "Estela", "Laúndos e Rates", "Póvoa de Varzim, Beiriz e Argivai"],
  "Santo Tirso": ["Agrela e Campo", "Areias, Sequeiró, Lama e Palmeira", "Carreira e Refojos de Riba de Ave", "Lamelas, Guimarei e Lama", "Monte Córdova", "Negrelos (São Mamede) e São Tomé de Negrelos", "Reguenga", "Roriz e Burgães", "Santo Tirso, Couto (Santa Cristina e São Miguel) e Burgães", "Vila das Aves"],
  "Trofa": ["Alvarelhos e Guidões", "Coronado (São Romão e São Mamede)", "Muro e São Romão de Coronado", "Trofa"],
  "Valongo": ["Alfena", "Campo e Sobrado", "Ermesinde", "Valongo"],
  "Vila do Conde": ["Árvore e Junqueira", "Azurara e Fornelo", "Bagunte, Ferreiró, Outeiro Maior e Parada", "Fajozes, Fornelo e Labruge", "Gião, Malta e Canidelo", "Guilhabreu e Modivas", "Macieira da Maia, Mindelo e Vila Chã", "Retorta e Tougues", "Rio Mau e Arcos", "Touguinha e Touguinhó", "Vairão", "Vila do Conde", "Vilar e Mosteiró", "Vilar de Pinheiro"],
  "Vila Nova de Gaia": ["Arcozelo", "Avintes", "Canelas", "Canidelo", "Grijó e Sermonde", "Gulpilhares e Valadares", "Madalena", "Mafamude e Vilar do Paraíso", "Oliveira do Douro", "Pedroso e Seixezelo", "Sandim, Olival, Lever e Crestuma", "Santa Marinha e São Pedro da Afurada", "São Félix da Marinha", "Serzedo e Perosinho", "Vilar de Andorinho"],

  // ==================== SANTARÉM ====================
  "Abrantes": ["Aldeia do Mato e Souto", "Alferrarede, Mouriscas, Fontes e Rossio ao Sul do Tejo", "Alvega e Concavada", "Bemposta", "Carvalhal", "Martinchel e Pego", "Rio de Moinhos", "São Facundo e Vale de Pedras", "São Miguel do Rio Torto e Terrugem", "Tramagal"],
  "Alcanena": ["Alcanena", "Bugalhos", "Louriceira e Espinheiro", "Malhou, Louriceira e Espinheiro", "Minde", "Moitas Venda, Minde e Serra de Santo António", "Serra de Santo António"],
  "Almeirim": ["Almeirim", "Benfica do Ribatejo", "Fazendas de Almeirim", "Raposa e Paço dos Negros"],
  "Alpiarça": ["Alpiarça"],
  "Benavente": ["Barrosa", "Benavente", "Samora Correia", "Santo Estêvão"],
  "Cartaxo": ["Cartaxo e Vale da Pinta", "Ereira e Lapa", "Pontével", "Valada", "Vila Chã de Ourique e Cardosos"],
  "Chamusca": ["Chamusca e Pinheiro Grande", "Chouto e Carregueira", "Parreira e Vale de Cavalos", "Ulme e Carregueira"],
  "Constância": ["Constância", "Montalvo e Santa Margarida", "Santa Margarida da Coutada"],
  "Coruche": ["Biscainho e São José da Lamarosa", "Coruche, Fajarda e Erra", "Couço", "Santana do Mato e São Torcato"],
  "Entroncamento": ["Entroncamento"],
  "Ferreira do Zêzere": ["Areias e Pias", "Chãos", "Ferreira do Zêzere", "Paio Mendes", "Águas Belas e Beco", "Igreja Nova do Sobral e Paio Mendes"],
  "Golegã": ["Azinhaga", "Golegã"],
  "Mação": ["Amêndoa, Cardigos e Carvoeiro", "Envendos e Ortiga", "Mação, Penhascoso e Aboboreira"],
  "Ourém": ["Alburitel, Espite e Nossa Senhora das Misericórdias", "Atouguia e Freixianda", "Caxarias e Seiça", "Fátima", "Gondemaria e Olival", "Matas e Cercal", "Nossa Senhora da Piedade e Formigais", "Nossa Senhora das Misericórdias", "Ourém", "Rio de Couros e Casal dos Bernardos", "Urqueira"],
  "Rio Maior": ["Alcobertas e Arrouquelas", "Arrouquelas", "Azambujeira e Malaqueijo", "Fráguas e São João da Ribeira", "Marmeleira e Assentiz", "Rio Maior", "São Sebastião e Asseiceira"],
  "Salvaterra de Magos": ["Foros de Salvaterra e Glória do Ribatejo", "Marinhais", "Muge", "Salvaterra de Magos e Granho"],
  "Santarém": ["Abitureiras", "Achete, Azóia de Baixo e Póvoa de Santarém", "Alcanede e Abrã", "Almoster", "Amiais de Baixo e Arneiro das Milhariças", "Azóia de Cima, Casével, Tremês e Vale de Santarém", "Gançaria", "Moçarria", "Pernes", "Romeira e Várzea", "Santarém (Marvila), Santa Iria da Ribeira de Santarém, Santarém (São Salvador) e Santarém (São Nicolau)", "São Vicente do Paul e Vale de Figueira", "Vale de Figueira"],
  "Sardoal": ["Alcaravela", "Sardoal", "Santiago de Montalegre e Valhascos"],
  "Tomar": ["Além da Ribeira e Pedreira", "Alviobeira e Carregueiros", "Asseiceira e Casais", "Madalena e Beselga", "Olalhas", "Paialvo e Junceira", "Sabacheira e Madalena", "São Pedro de Tomar", "Serra e Junceira", "Tomar (São João Baptista) e Santa Maria dos Olivais"],
  "Torres Novas": ["Assentis, Brogueira, Parceiros de Igreja e Alcorochel", "Chancelaria", "Lapas e Ribeira Branca", "Meia Via e Olaia", "Pedrógão, Zibreira e Minde", "Riachos", "São Pedro, Santiago e Santa Maria", "Torres Novas (Santa Maria, Salvador e Santiago)", "Zibreira"],
  "Vila Nova da Barquinha": ["Atalaia e Moitas Venda", "Praia do Ribatejo e Tancos", "Vila Nova da Barquinha"],

  // ==================== SETÚBAL ====================
  "Alcácer do Sal": ["Alcácer do Sal (Santa Maria do Castelo e Santiago) e Santa Susana", "Comporta", "São Martinho e Torrão", "Torção e Grândola"],
  "Alcochete": ["Alcochete", "Samouco"],
  "Almada": ["Almada, Cova da Piedade, Pragal e Cacilhas", "Caparica e Trafaria", "Charneca de Caparica e Sobreda", "Costa da Caparica", "Laranjeiro e Feijó"],
  "Barreiro": ["Alto do Seixalinho, Santo André e Verderena", "Barreiro e Lavradio", "Palhais e Coina", "Santo António da Charneca"],
  "Grândola": ["Azinheira dos Barros e São Mamede do Sádão", "Carvalhal", "Grândola e Santa Margarida da Serra", "Melides"],
  "Moita": ["Alhos Vedros", "Baixa da Banheira e Vale da Amoreira", "Moita e Gaio-Rosário", "Sarilhos Pequenos"],
  "Montijo": ["Alto-Estanqueiro-Jardia", "Atalaia e Sarilhos Grandes", "Canha", "Montijo e Afonsoeiro", "Pegões", "Santo Isidro de Pegões"],
  "Palmela": ["Marateca", "Palmela", "Pinhal Novo", "Quinta do Anjo"],
  "Santiago do Cacém": ["Abela", "Alvalade", "Cercal do Alentejo", "Ermidas-Sado e Santo André", "São Domingos e Vale de Água", "Santiago do Cacém, Santa Cruz e São Bartolomeu da Serra"],
  "Seixal": ["Aldeia de Paio Pires", "Amora", "Corroios", "Fernão Ferro", "Seixal, Arrentela e Aldeia de Paio Pires"],
  "Sesimbra": ["Castelo", "Quinta do Conde", "Santiago"],
  "Setúbal": ["Azeitão (São Lourenço e São Simão)", "Gâmbia, Pontes e Alto da Guerra", "Sado", "São Sebastião", "Setúbal (São Julião, Nossa Senhora da Anunciada e Santa Maria da Graça)"],
  "Sines": ["Porto Covo", "Sines"],

  // ==================== VIANA DO CASTELO ====================
  "Arcos de Valdevez": ["Aboim, Arcos de Valdevez (Salvador), Eiras, Loureda, Prozelo, São Victor, Senharei, Soajo e Tabaçô", "Aguiã, Couto e Âncora", "Cabana Maior", "Cabreiro e Álvora", "Cendufe", "Couto", "Extremo e Giela", "Gavieira", "Grade e Carralcova", "Guilhadeses e Santar", "Jolda (Madalena) e Rio Cabrão", "Miranda e Padreiro (Salvador e Santa Rita)", "Monte Redondo e Carmo", "Oliveira, Ardegão e Portela", "Padroso e Sistelo", "Parada e Vilela", "Portela e Sabadim", "Rio Frio", "Rio de Moinhos e Sabadim", "Santar e Arcos de Valdevez (São Paio)", "Senharei e Távora (Santa Maria e São Vicente)", "Souto e Gondariz", "Vale"],
  "Caminha": ["Âncora", "Arga (Baixo, Cima e São João)", "Azevedo e Lanhelas", "Caminha (Matriz) e Vilarelho", "Cristelo Covo, Dem e Riba de Âncora", "Moledo e Cristelo", "Seixas", "Vila Praia de Âncora e Vile", "Vilar de Mouros e Gondar"],
  "Melgaço": ["Alvaredo", "Castro Laboreiro e Lamas de Mouro", "Chaviães e Paços", "Cousso, Prado e Gave", "Cristoval e Penso", "Melgaço e Paderne", "Prado", "Remoães e Fiães"],
  "Monção": ["Anhões e Luzio", "Barbeita", "Bela e Longos Vales", "Cambeses e Abedim", "Ceivães e Tangil", "Lapela e Segude", "Mazedo e Cortes", "Merufe e Portela", "Messegães, Valadares e Sá", "Monção e Troviscoso", "Pinheiros", "Podame, Riba de Mouro e Trute", "Sago, Lordelo e Parada", "Tangil e Troporiz"],
  "Paredes de Coura": ["Agualonga e Infesta", "Bico e Cristelo", "Castanheira e Formariz", "Cossourado e Linhares", "Coura, Cunha e Porreiras", "Ferreira, Insalde e Paredes de Coura", "Mozelos e Padornelo", "Parada e Resende", "Romarigães e Rubiães"],
  "Ponte da Barca": ["Azias, Cuide de Vila Verde e Vila Chã", "Boivães e Lindoso", "Bravães e Jolda (São Paio)", "Britelo, Crasto e Ruivos", "Entre Ambos-os-Rios, Ermida e Germil", "Lavradas e Oleiros", "Nogueira e Sampriz", "Paço Vedro de Magalhães e Ponte da Barca", "São João Baptista de Vila Chã, Touvedo (Santa Maria e Salvador)", "Vade (São Pedro e São Tomé) e Vila Nova de Muía"],
  "Ponte de Lima": ["Arca e Ponte de Lima", "Arcozelo, Fontão e Cabração", "Ardegão, Freixo e Mato", "Associação de Freguesias do Vale do Neiva", "Bárrio e Cepões", "Beiral do Lima e Moreira do Lima", "Bertiandos e Sá", "Boalhosa", "Brandara e Facha", "Cabaços e Fojo Lobal", "Cabração", "Calheiros", "Calvelo e Fojo Lobal", "Feitosa, Gândara e Gemieira", "Fornelos e Queijada", "Friastelas", "Labruja e Rendufe", "Navió e Vitorino dos Piães", "Refóios do Lima, Ponte de Lima, Arcozelo e Fornelos", "Ribeira e Freixo", "Santa Comba e Rebordões (Souto)", "Santa Cruz do Lima e São Martinho de Gandra", "Sandiães, Correlhã e Gondufe", "Seara e Cepões", "Serdedelo e Estorãos", "Vilar do Monte e Mosteiró"],
  "Valença": ["Arão, Cristelo Covo e Fontoura", "Boivão, Cerdal, Ganfei e Gondomil", "Fontoura, Friestas e Verdoejo", "Gandra, Taião, São Julião e Silva", "Sanfins e São Pedro da Torre", "Valença, Cristelo Covo e Arão"],
  "Viana do Castelo": ["Afife", "Alvarães", "Amonde e Santa Leocádia de Geraz do Lima", "Areosa e Darque", "Barroselas e Carvoeiro", "Cardielos e Serreleis", "Castelo do Neiva e Freixieiro de Soutelo", "Chafé", "Deocriste e Portela Susã", "Geraz do Lima (Santa Maria, Santa Leocádia e Moreira) e Deão", "Lanheses e Nogueira", "Mazarefes e Vila Fria", "Meadela e Perre", "Montaria", "Mujães", "Neiva, Outeiro e Torre", "Perre", "Santa Marta de Portuzelo e Meadela", "Subportela e Deocriste", "Vila de Punhe e Portuzelo", "Vila Franca, Carreço e Areosa", "Viana do Castelo (Santa Maria Maior e Monserrate) e Meadela"],
  "Vila Nova de Cerveira": ["Candemil e Gondar", "Campos, Loivo, Mentrestido e Sapardos", "Cerveira, Lovelhe e Sopo", "Cornes, Covas e Reboreda", "Vila Meã, Loivo e Gondarém", "Vila Nova de Cerveira e Lanhelas"],

  // ==================== VILA REAL ====================
  "Alijó": ["Alijó", "Amieiro e Carlão", "Castedo e Cotas", "Favaios", "Pegarinhos e São Mamede de Ribatua", "Pinhão e Sanfins do Douro", "Pópulo e Ribalonga", "Santa Eugénia", "São Mamede de Ribatua", "Vila Chã de Além e Vilar de Maçada", "Vila Verde e Vilarinho de Cotas"],
  "Boticas": ["Alturas do Barroso e Cerdedo", "Ardãos e Bobadela", "Beça", "Boticas e Granja", "Codessoso, Curros e Fiães do Tâmega", "Dornelas", "Pinho e Sapiãos", "Vilar e Viveiro"],
  "Chaves": ["Anelhe", "Arcossó, Curalha e Oucidres", "Bobadela", "Bustelo, Cela e Mairos", "Calvão e Soutelinho da Raia", "Chaves", "Ervededo e Samaiões", "Faiões", "Lama de Arcos e Sanjurge", "Madalena e Samaiões", "Moreiras, Oura, Póvoa de Agrações e Vilar de Nantes", "Nogueira da Montanha", "Outeiro Seco", "Paradela de Monforte e Redondelo", "Planalto de Monforte (Águas Frias, Cimo de Vila da Castanheira, Eiras, Santa Cruz-Trindade e São Pedro de Agostém)", "Redondelo", "Sanfins e Vidago", "Santa Maria Maior", "Santo Estêvão", "Seara Velha", "Selhariz e Vila Meã", "Soutelo e Vilarelho da Raia", "Tronco, Oucidres e Travancas", "Valdanta, Vilas Boas e Vilela Seca", "Vila Verde da Raia e Vilar de Perdizes", "Vilela e Anelhe", "Vilarelho da Raia"],
  "Mesão Frio": ["Barqueiros e Cidadelhe", "Mesão Frio (Santo André)", "Oliveira e Vila Marim"],
  "Mondim de Basto": ["Atei e Mondim de Basto", "Bilhó e Ermelo", "Campanhó e Paradança", "Vilar de Ferreiros e São Cristóvão de Mondim"],
  "Montalegre": ["Cabril, Gralhas e Meixide", "Cambeses do Rio e Donões", "Cervos, Solveira e Padroso", "Chã", "Ferral e Outeiro", "Meixedo e Padornelos", "Montalegre e Padroso", "Morgade, Negrões, Mourilhe e Venda Nova", "Pitões das Júnias e Tourém", "Reigoso, Fervidelas e Ferral", "Salto", "Santo André, Sarraquinhos, Gralhas e Cabril", "Sezelhe e Covelães", "Vilar de Perdizes"],
  "Peso da Régua": ["Fontelas e Loureiro", "Galafura e Covelinhas", "Godim", "Moura Morta, Vinhós e Poiares", "Peso da Régua e Godim", "Sedielos e Vilarinho de Freires"],
  "Ribeira de Pena": ["Alvadia e Santa Leocádia", "Cerva e Limões", "Ribeira de Pena (Salvador) e Santo Aleixo de Além-Tâmega"],
  "Sabrosa": ["Celeirós e Provesende", "Covas do Douro e Parada de Pinhão", "Gouvinhas e Sabrosa", "São Cristóvão do Douro, São Martinho de Antas e Vilarinho de São Romão", "Souto Maior e Torre do Pinhão"],
  "Santa Marta de Penaguião": ["Alvações do Corgo e Cumieira", "Fontes e Louredo", "Medrões", "Santa Marta de Penaguião e Sever"],
  "Valpaços": ["Água Revés e Crasto", "Barreiros e Vales", "Bouçoães e Curros", "Carrazedo de Montenegro e Tazem", "Ervões e Santa Maria de Émeres", "Friões e Nunes", "Lebução, Fiães e Nozelos", "Rio Torto", "Santa Valha, Canaveses e Possacos", "Sanfins e Sonim", "Valpaços e Sanfins", "Vassal e Santa Valha", "Veiga de Lila, Padrela e Tazem", "Vilarandelo e Vales"],
  "Vila Pouca de Aguiar": ["Alfarela de Jales e Vreia de Jales", "Alvão e Gouvães da Serra", "Bornes de Aguiar e Telões", "Bragado e Capeludos", "Pensalvos e Parada de Monteiros", "Sabroso de Aguiar, Vila Pouca de Aguiar e Soutelo de Aguiar", "Santa Maria de Émeres e Tresminas", "Valoura"],
  "Vila Real": ["Abaças e Sanfins", "Adoufe e Vilarinho de Samardã", "Andrães", "Arroios e Folhadela", "Borbela e Lamas de Olo", "Campeã e Vila Marim", "Constantim e Vale de Nogueiras", "Guiães", "Lordelo e Mouçós", "Mateus", "Mondrões e Ermida", "Nossa Senhora da Conceição, São Pedro e São Dinis", "Parada de Cunhos e Vila Cova", "Torgueda e Lamas de Olo", "Vila Real"],

  // ==================== VISEU ====================
  "Armamar": ["Aldeias e Aricera", "Armamar e Vacalar", "Cimbres e Fontelo", "Folgosa e Santa Cruz", "Goujoim e S. Cosmado", "São Martinho das Chãs e São Romão"],
  "Carregal do Sal": ["Beijós", "Cabanas de Viriato e Carregal do Sal", "Currelos, Papízios e Sobral", "Oliveira do Conde e Carvalhal Redondo"],
  "Castro Daire": ["Almofala", "Castro Daire", "Cujó e Parada de Ester", "Gosende, Reriz e Pinheiro", "Mamouros, Alva e Moledo", "Mões e Ermida", "Monteiras e Pepim", "Parada de Ester", "Pinheiro", "Picão e Ribeira de Pena"],
  "Cinfães": ["Cinfães", "Ferreiros de Tendais e Tendais", "Fornelos e Souselo", "Moimenta e Meridões", "Nespereira, Fornelos e Ramires", "Oliveira do Douro e Louredo", "Santiago de Piães e Travanca", "São Cristóvão de Nogueira e Tarouquela"],
  "Lamego": ["Almacave e Sé", "Avões e Parada do Bispo", "Britiande e Cambres", "Cepões, Meijinhos e Bigorne", "Figueira de Castelo Rodrigo", "Lalim e Vila Nova de Souto d'El-Rei", "Lazarim, Penude, Vila Nova de Souto d'El-Rei, Várzea de Abrunhais e Almacave", "Magueija e Penajóia", "Parada do Bispo", "Penude e Ferreirim", "Sande e São Romão de Aregos", "Valdigem, Lamego e Melcões"],
  "Mangualde": ["Abrunhosa-a-Velha e Cunha Alta", "Alcafache e Fornos de Maceira Dão", "Cunha Baixa e Espinho", "Freixiosa e Tavares", "Mangualde, Mesquitela e Cunha Alta", "Quintela de Azurara", "Santiago de Cassurrães e Póvoa de Cervães", "São João da Fresta e Moimenta de Maceira Dão"],
  "Moimenta da Beira": ["Aldeia de Nacomba e Alvite", "Ariz e Sarzedo", "Baldos e Arcozelos", "Cabaços e Castelo", "Caria", "Leomil, Pêra Velha e Paradinha", "Moimenta da Beira e Arcozelos", "Paradinha e Nagosa", "Passô e Sever", "Peva e Vilar", "Rua e Nagosa", "Sarzedo", "Sever e Aldeia de Nacomba"],
  "Mortágua": ["Cercosa e Marmeleira", "Espinho e Vale de Madeiros", "Mortágua", "Pala e Trezói", "Sobral e Trezói"],
  "Nelas": ["Aguieira e Moreira", "Canas de Senhorim e Lapa do Lobo", "Carvalhal Redondo e Aguieira", "Nelas, Vilar Seco e Canas de Sabugosa", "Santar e Moreira"],
  "Oliveira de Frades": ["Arca e Varzielas", "Destriz e Reigoso", "Oliveira de Frades e Souto de Lafões", "Pinheiro e S. João de Lourosa", "Ribeiradio e Sejães", "São João da Serra e Arcozelo das Maias"],
  "Penalva do Castelo": ["Antas e Pindo", "Esmolfe e Matela", "Ínsua", "Lusinde", "Penalva do Castelo e Real"],
  "Penedono": ["Antas e Ourozinho", "Castainço e Penela da Beira", "Granja e Souto", "Penedono e Beselga", "Póvoa de Penela e Souto de Penedono"],
  "Resende": ["Anreade e São Cipriano", "Cárquere e São Martinho de Mouros", "Felgueiras e Freigil", "Ovadas e Panchorra", "Resende e Miomães", "São João de Fontoura e Barrô", "São Romão de Aregos e Cárquere"],
  "Santa Comba Dão": ["Couto do Mosteiro e São João de Areias", "Ovoa e Vimieiro", "Pinheiro de Ázere e São Joaninho", "Santa Comba Dão e Treixedo"],
  "São João da Pesqueira": ["Castanheiro do Sul e Paredes da Beira", "Ervedosa do Douro e Nagozelo", "Espinhosa, Soutelo do Douro e Sarzedinho", "São João da Pesqueira e Várzea de Trevões", "Trevões e Riodades", "Vale de Figueira e Vale de Figueira", "Valongo dos Azeites e Vilarouco"],
  "São Pedro do Sul": ["Baiões e Covas do Rio", "Bordonhos, Fataúnços e Pindo", "Carvalhais e Candal", "Covas do Rio", "Manhouce e Pindelo dos Milagres", "Papízios e Bordonhos", "Pinho e Santo Estêvão", "Santiago de Besteiros e Serrazes", "São Cristóvão de Lafões e Santa Cruz da Trapa", "São Félix e Várzea", "São Pedro do Sul, Várzea e Baiões", "Sul, Santa Cruz da Trapa e São Cristóvão de Lafões", "Valadares, Figueiredo das Donas e Carvalhais"],
  "Sátão": ["Avelal e Romãs", "Ferreira de Aves e Sátão", "Mioma, Silvã de Cima e São Miguel de Vila Boa", "Rio de Moinhos e Casfreires"],
  "Sernancelhe": ["Arnas, Fonte Arcada e Faia", "Carregal, Quintela e Vila da Ponte", "Faia e Granjal", "Freixinho e Vila da Ponte", "Lamosa e Penso", "Sernancelhe e Arnas", "Tabosa do Carregal e Macieira"],
  "Tabuaço": ["Adorigo e Barcos", "Arcos, Chavães e Granjinha", "Desejosa", "Longa e Várzea da Serra", "Sendim e Tabuaço", "Valença do Douro"],
  "Tarouca": ["Dalvares e Mondim da Beira", "Gouviães e Ucanha", "Granja Nova e Vila Chã da Beira", "São João de Tarouca e Várzea da Serra", "Tarouca e Dálvares"],
  "Tondela": ["Campo de Besteiros e Lobão da Beira", "Canas de Santa Maria e Caparrosa", "Ferreirós do Dão e Molelos", "Guardão e Mosteirinho", "Lajeosa do Dão e Parada de Gonta", "Nandufe e Castelões", "Sabugosa e Vilar de Besteiros", "Santiago de Besteiros e São Miguel do Outeiro", "Tonda e Tourigo", "Tondela e Mouraz", "Vila Nova da Rainha e Tonda"],
  "Vila Nova de Paiva": ["Alhais e Fráguas", "Pendilhe e Touro", "Queiriga e Vila Cova à Coelheira", "Vila Nova de Paiva e Alhais"],
  "Viseu": ["Abraveses", "Barreiros e Cepões", "Boaldeia e Coutos de Viseu", "Boa Aldeia, Farminhão e Torredeita", "Cavernães", "Campo e Cota de Viseu", "Coração de Jesus", "Fragosela, Povolide e Rio de Loba", "Lordosa e Santos Evos", "Mundão e Cavernães", "Orgens e Vildemoinhos", "Povolide", "Ranhados", "Repeses e São Salvador", "Ribafeita e São João de Lourosa", "Rio de Loba", "Santos Evos", "São Cipriano e Vil de Souto", "São João de Lourosa e Silgueiros", "São José", "São Pedro de France e Calde", "Silgueiros e Fragosela", "Torredeita", "Vila Chã de Sá e Coutos de Viseu", "Vildemoinhos e Viseu"],
  "Vouzela": ["Alcofra e Fataúnços", "Cambra e Queirã", "Campia, Fornelo do Monte e Paços de Vilharigues", "Ventosa e Fataunços", "Vouzela e Paços de Vilharigues"]
};

export const TIPOS_IMOVEL = [
  { value: "moradia", labelKey: "moradia", label: "Moradia" },
  { value: "apartamento", labelKey: "apartamento", label: "Apartamento" },
  { value: "casa", labelKey: "casa", label: "Casa" },
  { value: "terreno", labelKey: "terreno", label: "Terreno" },
  { value: "escritorio", labelKey: "escritorio", label: "Escritório" },
  { value: "comercial", labelKey: "comercial", label: "Comercial" },
  { value: "industrial", labelKey: "industrial", label: "Industrial" },
  { value: "armazem", labelKey: "armazem", label: "Armazém" },
  { value: "loja", labelKey: "loja", label: "Loja" },
  { value: "garagem", labelKey: "garagem", label: "Garagem" },
  { value: "quinta", labelKey: "quinta", label: "Quinta" },
  {
    value: "terreno_urbano",
    labelKey: "terreno_urbano",
    label: "Terreno Urbano",
  },
  {
    value: "terreno_rustico",
    labelKey: "terreno_rustico",
    label: "Terreno Rústico",
  },
];
