export const DISTRITOS = [
  "Aveiro",
  "Beja",
  "Braga",
  "Bragança",
  "Castelo Branco",
  "Coimbra",
  "Évora",
  "Faro",
  "Guarda",
  "Leiria",
  "Lisboa",
  "Portalegre",
  "Porto",
  "Santarém",
  "Setúbal",
  "Viana do Castelo",
  "Vila Real",
  "Viseu",
];

export const DISTRITO_MUNICIPIOS: { [key: string]: string[] } = {
  Aveiro: [
    "Águeda",
    "Albergaria-a-Velha",
    "Anadia",
    "Arouca",
    "Aveiro",
    "Castelo de Paiva",
    "Espinho",
    "Estarreja",
    "Ílhavo",
    "Mealhada",
    "Murtosa",
    "Oliveira de Azeméis",
    "Oliveira do Bairro",
    "Ovar",
    "Santa Maria da Feira",
    "São João da Madeira",
    "Sever do Vouga",
    "Vagos",
    "Vale de Cambra",
  ],
  Beja: [
    "Aljustrel",
    "Almodôvar",
    "Alvito",
    "Barrancos",
    "Beja",
    "Castro Verde",
    "Cuba",
    "Ferreira do Alentejo",
    "Mértola",
    "Moura",
    "Odemira",
    "Ourique",
    "Serpa",
    "Vidigueira",
  ],
  Braga: [
    "Amares",
    "Barcelos",
    "Braga",
    "Cabeceiras de Basto",
    "Fafe",
    "Guimarães",
    "Póvoa de Lanhoso",
    "Terras de Bouro",
    "Vieira do Minho",
    "Vila Nova de Famalicão",
    "Vila Verde",
  ],
  Bragança: [
    "Alfândega da Fé",
    "Bragança",
    "Carrazeda de Ansiães",
    "Freixo de Espada à Cinta",
    "Macedo de Cavaleiros",
    "Miranda do Douro",
    "Mirandela",
    "Mogadouro",
    "Torre de Moncorvo",
    "Vila Flor",
    "Vimioso",
    "Vinhais",
  ],
  "Castelo Branco": [
    "Belmonte",
    "Castelo Branco",
    "Covilhã",
    "Fundão",
    "Idanha-a-Nova",
    "Oleiros",
    "Penamacor",
    "Proença-a-Nova",
    "Sertã",
    "Vila de Rei",
    "Vila Velha de Ródão",
  ],
  Coimbra: [
    "Arganil",
    "Cantanhede",
    "Coimbra",
    "Condeixa-a-Nova",
    "Figueira da Foz",
    "Góis",
    "Lousã",
    "Mira",
    "Miranda do Corvo",
    "Montemor-o-Velho",
    "Oliveira do Hospital",
    "Penacova",
    "Pombal",
    "Soure",
  ],
  Évora: [
    "Alandroal",
    "Arraiolos",
    "Borba",
    "Estremoz",
    "Évora",
    "Montemor-o-Novo",
    "Moura",
    "Portel",
    "Redondo",
    "Reguengos de Monsaraz",
    "Vendas Novas",
    "Viana do Alentejo",
    "Vila Viçosa",
  ],
  Faro: [
    "Albufeira",
    "Alcoutim",
    "Aljezur",
    "Castro Marim",
    "Faro",
    "Lagoa",
    "Lagos",
    "Loulé",
    "Monchique",
    "Olhão",
    "Portimão",
    "São Brás de Alportel",
    "Silves",
    "Tavira",
    "Vila do Bispo",
    "Vila Real de Santo António",
  ],
  Guarda: [
    "Aguiar da Beira",
    "Almeida",
    "Celorico da Beira",
    "Figueira de Castelo Rodrigo",
    "Guarda",
    "Manteigas",
    "Mêda",
    "Pinhel",
    "Sabugal",
    "Seia",
    "Trancoso",
  ],
  Leiria: [
    "Alcobaça",
    "Alvaiázere",
    "Ansião",
    "Batalha",
    "Bombarral",
    "Caldas da Rainha",
    "Castanheira de Pera",
    "Figueiró dos Vinhos",
    "Leiria",
    "Marinha Grande",
    "Nazaré",
    "Óbidos",
    "Pedrógão Grande",
    "Peniche",
    "Pombal",
  ],
  Lisboa: [
    "Alenquer",
    "Amadora",
    "Arruda dos Vinhos",
    "Azambuja",
    "Cadaval",
    "Cascais",
    "Lisboa",
    "Loures",
    "Lourinhã",
    "Mafra",
    "Odivelas",
    "Oeiras",
    "Sintra",
    "Sobral de Monte Agraço",
    "Torres Vedras",
  ],
  Portalegre: [
    "Alter do Chão",
    "Arronches",
    "Avis",
    "Campo Maior",
    "Castelo de Vide",
    "Crato",
    "Elvas",
    "Fronteira",
    "Gavião",
    "Marvão",
    "Monforte",
    "Nisa",
    "Portalegre",
  ],
  Porto: [
    "Amarante",
    "Baixa da Banheira",
    "Barcelos",
    "Braga",
    "Câmara de Lobos",
    "Felgueiras",
    "Gondomar",
    "Lousada",
    "Maia",
    "Matosinhos",
    "Paços de Ferreira",
    "Paredes",
    "Penafiel",
    "Porto",
    "Póvoa de Varzim",
    "Santo Tirso",
    "Trofa",
    "Valongo",
    "Vila do Conde",
    "Vila Nova de Gaia",
  ],
  Santarém: [
    "Abrantes",
    "Alcanena",
    "Almeirim",
    "Benavente",
    "Cartaxo",
    "Chamusca",
    "Constância",
    "Coruche",
    "Entroncamento",
    "Ferreira do Zêzere",
    "Golegã",
    "Mação",
    "Ourém",
    "Rio Maior",
    "Salvaterra de Magos",
    "Santarém",
    "Sardoal",
    "Tomar",
    "Torres Novas",
  ],
  Setúbal: [
    "Alcácer do Sal",
    "Alcochete",
    "Almada",
    "Barreiro",
    "Grândola",
    "Moita",
    "Montijo",
    "Palmela",
    "Santiago do Cacém",
    "Seixal",
    "Setúbal",
    "Sesimbra",
    "Sines",
  ],
  "Viana do Castelo": [
    "Arcos de Valdevez",
    "Caminha",
    "Melgaço",
    "Monção",
    "Paredes de Coura",
    "Ponte de Lima",
    "Viana do Castelo",
    "Vila Nova de Cerveira",
  ],
  "Vila Real": [
    "Alijó",
    "Boticas",
    "Chaves",
    "Mesão Frio",
    "Mondim de Basto",
    "Montalegre",
    "Peso da Régua",
    "Ribeira de Pena",
    "Sabrosa",
    "Santa Marta de Penaguião",
    "Valpaços",
    "Vila Pouca de Aguiar",
    "Vila Real",
  ],
  Viseu: [
    "Armamar",
    "Carregal do Sal",
    "Castro Daire",
    "Cinfães",
    "Lamego",
    "Mangualde",
    "Moimenta da Beira",
    "Nelas",
    "Oliveira de Frades",
    "Penalva do Castelo",
    "Penedono",
    "Resende",
    "Santa Comba Dão",
    "São João da Pesqueira",
    "Sátão",
    "Tondela",
    "Vila Nova de Paiva",
    "Viseu",
  ],
};

export const TIPOS_IMOVEL = [
  { value: "moradia", label: "Moradia" },
  { value: "apartamento", label: "Apartamento" },
  { value: "casa", label: "Casa" },
  { value: "terreno", label: "Terreno" },
  { value: "escritorio", label: "Escritório" },
  { value: "comercial", label: "Comercial" },
  { value: "industrial", label: "Industrial" },
  { value: "armazem", label: "Armazém" },
  { value: "loja", label: "Loja" },
  { value: "garagem", label: "Garagem" },
  { value: "quinta", label: "Quinta" },
  { value: "terreno_urbano", label: "Terreno Urbano" },
  { value: "terreno_rustico", label: "Terreno Rústico" },
];
